// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_AIVISION_IPC_H_
#define FLATBUFFERS_GENERATED_COMMON_AIVISION_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace aivision {
namespace ipc {

struct Point;

struct FixedPolygon;

struct BoundingBoxInfo;
struct BoundingBoxInfoBuilder;

struct PolygonInfo;
struct PolygonInfoBuilder;

/// 告警级别枚举
enum class AlarmLevel : int8_t {
  Info = 0,
  Warning = 1,
  Critical = 2,
  MIN = Info,
  MAX = Critical
};

inline const AlarmLevel (&EnumValuesAlarmLevel())[3] {
  static const AlarmLevel values[] = {
    AlarmLevel::Info,
    AlarmLevel::Warning,
    AlarmLevel::Critical
  };
  return values;
}

inline const char * const *EnumNamesAlarmLevel() {
  static const char * const names[4] = {
    "Info",
    "Warning",
    "Critical",
    nullptr
  };
  return names;
}

inline const char *EnumNameAlarmLevel(AlarmLevel e) {
  if (::flatbuffers::IsOutRange(e, AlarmLevel::Info, AlarmLevel::Critical)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAlarmLevel()[index];
}

/// 记录类型枚举
enum class RecordType : int8_t {
  Capture = 0,
  Recognition = 1,
  Alarm = 2,
  MIN = Capture,
  MAX = Alarm
};

inline const RecordType (&EnumValuesRecordType())[3] {
  static const RecordType values[] = {
    RecordType::Capture,
    RecordType::Recognition,
    RecordType::Alarm
  };
  return values;
}

inline const char * const *EnumNamesRecordType() {
  static const char * const names[4] = {
    "Capture",
    "Recognition",
    "Alarm",
    nullptr
  };
  return names;
}

inline const char *EnumNameRecordType(RecordType e) {
  if (::flatbuffers::IsOutRange(e, RecordType::Capture, RecordType::Alarm)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRecordType()[index];
}

/// 流状态枚举
enum class StreamStatus : int8_t {
  Pending = 0,
  Running = 1,
  Reconnecting = 2,
  Stopped = 3,
  Failed = 4,
  MIN = Pending,
  MAX = Failed
};

inline const StreamStatus (&EnumValuesStreamStatus())[5] {
  static const StreamStatus values[] = {
    StreamStatus::Pending,
    StreamStatus::Running,
    StreamStatus::Reconnecting,
    StreamStatus::Stopped,
    StreamStatus::Failed
  };
  return values;
}

inline const char * const *EnumNamesStreamStatus() {
  static const char * const names[6] = {
    "Pending",
    "Running",
    "Reconnecting",
    "Stopped",
    "Failed",
    nullptr
  };
  return names;
}

inline const char *EnumNameStreamStatus(StreamStatus e) {
  if (::flatbuffers::IsOutRange(e, StreamStatus::Pending, StreamStatus::Failed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStreamStatus()[index];
}

/// 自检状态枚举
enum class SelfCheckStatus : int8_t {
  Pending = 0,
  Running = 1,
  Passed = 2,
  Failed = 3,
  MIN = Pending,
  MAX = Failed
};

inline const SelfCheckStatus (&EnumValuesSelfCheckStatus())[4] {
  static const SelfCheckStatus values[] = {
    SelfCheckStatus::Pending,
    SelfCheckStatus::Running,
    SelfCheckStatus::Passed,
    SelfCheckStatus::Failed
  };
  return values;
}

inline const char * const *EnumNamesSelfCheckStatus() {
  static const char * const names[5] = {
    "Pending",
    "Running",
    "Passed",
    "Failed",
    nullptr
  };
  return names;
}

inline const char *EnumNameSelfCheckStatus(SelfCheckStatus e) {
  if (::flatbuffers::IsOutRange(e, SelfCheckStatus::Pending, SelfCheckStatus::Failed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSelfCheckStatus()[index];
}

/// 解码硬件类型枚举
enum class DecodeHWType : int8_t {
  Auto = 0,
  RKMPP = 1,
  DVPP = 2,
  FFmpeg = 3,
  MIN = Auto,
  MAX = FFmpeg
};

inline const DecodeHWType (&EnumValuesDecodeHWType())[4] {
  static const DecodeHWType values[] = {
    DecodeHWType::Auto,
    DecodeHWType::RKMPP,
    DecodeHWType::DVPP,
    DecodeHWType::FFmpeg
  };
  return values;
}

inline const char * const *EnumNamesDecodeHWType() {
  static const char * const names[5] = {
    "Auto",
    "RKMPP",
    "DVPP",
    "FFmpeg",
    nullptr
  };
  return names;
}

inline const char *EnumNameDecodeHWType(DecodeHWType e) {
  if (::flatbuffers::IsOutRange(e, DecodeHWType::Auto, DecodeHWType::FFmpeg)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDecodeHWType()[index];
}

/// 像素坐标点
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Point FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;

 public:
  struct Traits;
  Point()
      : x_(0),
        y_(0) {
  }
  Point(int32_t _x, int32_t _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  int32_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Point, 8);

struct Point::Traits {
  using type = Point;
};

/// 自定义固长多边形顶点数组 (最大8个顶点，不足用(0,0)填充)
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) FixedPolygon FLATBUFFERS_FINAL_CLASS {
 private:
  aivision::ipc::Point v0_;
  aivision::ipc::Point v1_;
  aivision::ipc::Point v2_;
  aivision::ipc::Point v3_;
  aivision::ipc::Point v4_;
  aivision::ipc::Point v5_;
  aivision::ipc::Point v6_;
  aivision::ipc::Point v7_;
  uint32_t count_;

 public:
  struct Traits;
  FixedPolygon()
      : v0_(),
        v1_(),
        v2_(),
        v3_(),
        v4_(),
        v5_(),
        v6_(),
        v7_(),
        count_(0) {
  }
  FixedPolygon(const aivision::ipc::Point &_v0, const aivision::ipc::Point &_v1, const aivision::ipc::Point &_v2, const aivision::ipc::Point &_v3, const aivision::ipc::Point &_v4, const aivision::ipc::Point &_v5, const aivision::ipc::Point &_v6, const aivision::ipc::Point &_v7, uint32_t _count)
      : v0_(_v0),
        v1_(_v1),
        v2_(_v2),
        v3_(_v3),
        v4_(_v4),
        v5_(_v5),
        v6_(_v6),
        v7_(_v7),
        count_(::flatbuffers::EndianScalar(_count)) {
  }
  const aivision::ipc::Point &v0() const {
    return v0_;
  }
  const aivision::ipc::Point &v1() const {
    return v1_;
  }
  const aivision::ipc::Point &v2() const {
    return v2_;
  }
  const aivision::ipc::Point &v3() const {
    return v3_;
  }
  const aivision::ipc::Point &v4() const {
    return v4_;
  }
  const aivision::ipc::Point &v5() const {
    return v5_;
  }
  const aivision::ipc::Point &v6() const {
    return v6_;
  }
  const aivision::ipc::Point &v7() const {
    return v7_;
  }
  uint32_t count() const {
    return ::flatbuffers::EndianScalar(count_);
  }
};
FLATBUFFERS_STRUCT_END(FixedPolygon, 68);

struct FixedPolygon::Traits {
  using type = FixedPolygon;
};

/// 检测框
struct BoundingBoxInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoundingBoxInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_W = 8,
    VT_H = 10,
    VT_CONFIDENCE = 12,
    VT_LABEL_ID = 14,
    VT_LABEL_NAME = 16,
    VT_TRACK_ID = 18
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  int32_t w() const {
    return GetField<int32_t>(VT_W, 0);
  }
  int32_t h() const {
    return GetField<int32_t>(VT_H, 0);
  }
  float confidence() const {
    return GetField<float>(VT_CONFIDENCE, 0.0f);
  }
  int32_t label_id() const {
    return GetField<int32_t>(VT_LABEL_ID, 0);
  }
  const ::flatbuffers::String *label_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL_NAME);
  }
  int32_t track_id() const {
    return GetField<int32_t>(VT_TRACK_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_W, 4) &&
           VerifyField<int32_t>(verifier, VT_H, 4) &&
           VerifyField<float>(verifier, VT_CONFIDENCE, 4) &&
           VerifyField<int32_t>(verifier, VT_LABEL_ID, 4) &&
           VerifyOffset(verifier, VT_LABEL_NAME) &&
           verifier.VerifyString(label_name()) &&
           VerifyField<int32_t>(verifier, VT_TRACK_ID, 4) &&
           verifier.EndTable();
  }
};

struct BoundingBoxInfoBuilder {
  typedef BoundingBoxInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_Y, y, 0);
  }
  void add_w(int32_t w) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_W, w, 0);
  }
  void add_h(int32_t h) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_H, h, 0);
  }
  void add_confidence(float confidence) {
    fbb_.AddElement<float>(BoundingBoxInfo::VT_CONFIDENCE, confidence, 0.0f);
  }
  void add_label_id(int32_t label_id) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_LABEL_ID, label_id, 0);
  }
  void add_label_name(::flatbuffers::Offset<::flatbuffers::String> label_name) {
    fbb_.AddOffset(BoundingBoxInfo::VT_LABEL_NAME, label_name);
  }
  void add_track_id(int32_t track_id) {
    fbb_.AddElement<int32_t>(BoundingBoxInfo::VT_TRACK_ID, track_id, 0);
  }
  explicit BoundingBoxInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoundingBoxInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoundingBoxInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoundingBoxInfo> CreateBoundingBoxInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t w = 0,
    int32_t h = 0,
    float confidence = 0.0f,
    int32_t label_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label_name = 0,
    int32_t track_id = 0) {
  BoundingBoxInfoBuilder builder_(_fbb);
  builder_.add_track_id(track_id);
  builder_.add_label_name(label_name);
  builder_.add_label_id(label_id);
  builder_.add_confidence(confidence);
  builder_.add_h(h);
  builder_.add_w(w);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct BoundingBoxInfo::Traits {
  using type = BoundingBoxInfo;
  static auto constexpr Create = CreateBoundingBoxInfo;
};

inline ::flatbuffers::Offset<BoundingBoxInfo> CreateBoundingBoxInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0,
    int32_t w = 0,
    int32_t h = 0,
    float confidence = 0.0f,
    int32_t label_id = 0,
    const char *label_name = nullptr,
    int32_t track_id = 0) {
  auto label_name__ = label_name ? _fbb.CreateString(label_name) : 0;
  return aivision::ipc::CreateBoundingBoxInfo(
      _fbb,
      x,
      y,
      w,
      h,
      confidence,
      label_id,
      label_name__,
      track_id);
}

/// 多边形区域
struct PolygonInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PolygonInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POINTS = 4
  };
  const ::flatbuffers::Vector<const aivision::ipc::Point *> *points() const {
    return GetPointer<const ::flatbuffers::Vector<const aivision::ipc::Point *> *>(VT_POINTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.EndTable();
  }
};

struct PolygonInfoBuilder {
  typedef PolygonInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_points(::flatbuffers::Offset<::flatbuffers::Vector<const aivision::ipc::Point *>> points) {
    fbb_.AddOffset(PolygonInfo::VT_POINTS, points);
  }
  explicit PolygonInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PolygonInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PolygonInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PolygonInfo> CreatePolygonInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const aivision::ipc::Point *>> points = 0) {
  PolygonInfoBuilder builder_(_fbb);
  builder_.add_points(points);
  return builder_.Finish();
}

struct PolygonInfo::Traits {
  using type = PolygonInfo;
  static auto constexpr Create = CreatePolygonInfo;
};

inline ::flatbuffers::Offset<PolygonInfo> CreatePolygonInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<aivision::ipc::Point> *points = nullptr) {
  auto points__ = points ? _fbb.CreateVectorOfStructs<aivision::ipc::Point>(*points) : 0;
  return aivision::ipc::CreatePolygonInfo(
      _fbb,
      points__);
}

}  // namespace ipc
}  // namespace aivision

#endif  // FLATBUFFERS_GENERATED_COMMON_AIVISION_IPC_H_
