// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMANDS_AIVISION_IPC_H_
#define FLATBUFFERS_GENERATED_COMMANDS_AIVISION_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace aivision {
namespace ipc {

struct AlgoBinding;
struct AlgoBindingBuilder;

struct LabelMapEntry;
struct LabelMapEntryBuilder;

struct StartStreamCmd;
struct StartStreamCmdBuilder;

struct StopStreamCmd;
struct StopStreamCmdBuilder;

struct UpdateAlgoConfigCmd;
struct UpdateAlgoConfigCmdBuilder;

struct UpdateStreamConfigCmd;
struct UpdateStreamConfigCmdBuilder;

struct HeartbeatCmd;
struct HeartbeatCmdBuilder;

struct ShutdownCmd;
struct ShutdownCmdBuilder;

struct StreamStartCmd;
struct StreamStartCmdBuilder;

struct StreamStopCmd;
struct StreamStopCmdBuilder;

struct StreamPlaybackStartCmd;
struct StreamPlaybackStartCmdBuilder;

struct StreamPlaybackStopCmd;
struct StreamPlaybackStopCmdBuilder;

struct StreamStatusCmd;
struct StreamStatusCmdBuilder;

struct StartSelfCheckCmd;
struct StartSelfCheckCmdBuilder;

/// 算法绑定参数
struct AlgoBinding FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AlgoBindingBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ALGO_NAME = 4,
    VT_ALGO_VERSION = 6,
    VT_PACKAGE_ID = 8,
    VT_SO_PATH = 10,
    VT_ALGO_PARAMS_JSON = 12,
    VT_ROI_REGIONS_JSON = 14,
    VT_MARK_REGIONS_JSON = 16,
    VT_LINE_REGIONS_JSON = 18,
    VT_SCHEDULE_ENABLED = 20,
    VT_SCHEDULE_START = 22,
    VT_SCHEDULE_END = 24,
    VT_SORT_ORDER = 26,
    VT_LABEL_MAPS = 28
  };
  const ::flatbuffers::String *algo_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_NAME);
  }
  const ::flatbuffers::String *algo_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_VERSION);
  }
  const ::flatbuffers::String *package_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PACKAGE_ID);
  }
  const ::flatbuffers::String *so_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SO_PATH);
  }
  /// 算法特定参数 (JSON 透传)
  const ::flatbuffers::String *algo_params_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_PARAMS_JSON);
  }
  /// ROI 多边形区域 (JSON 透传)
  const ::flatbuffers::String *roi_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROI_REGIONS_JSON);
  }
  /// MARK 屏蔽区域 (JSON 透传)
  const ::flatbuffers::String *mark_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MARK_REGIONS_JSON);
  }
  /// LINE 绊线区域 (JSON 透传)
  const ::flatbuffers::String *line_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LINE_REGIONS_JSON);
  }
  bool schedule_enabled() const {
    return GetField<uint8_t>(VT_SCHEDULE_ENABLED, 0) != 0;
  }
  const ::flatbuffers::String *schedule_start() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCHEDULE_START);
  }
  const ::flatbuffers::String *schedule_end() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCHEDULE_END);
  }
  int32_t sort_order() const {
    return GetField<int32_t>(VT_SORT_ORDER, 0);
  }
  /// Label 映射表
  const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>> *label_maps() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>> *>(VT_LABEL_MAPS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ALGO_NAME) &&
           verifier.VerifyString(algo_name()) &&
           VerifyOffsetRequired(verifier, VT_ALGO_VERSION) &&
           verifier.VerifyString(algo_version()) &&
           VerifyOffsetRequired(verifier, VT_PACKAGE_ID) &&
           verifier.VerifyString(package_id()) &&
           VerifyOffsetRequired(verifier, VT_SO_PATH) &&
           verifier.VerifyString(so_path()) &&
           VerifyOffset(verifier, VT_ALGO_PARAMS_JSON) &&
           verifier.VerifyString(algo_params_json()) &&
           VerifyOffset(verifier, VT_ROI_REGIONS_JSON) &&
           verifier.VerifyString(roi_regions_json()) &&
           VerifyOffset(verifier, VT_MARK_REGIONS_JSON) &&
           verifier.VerifyString(mark_regions_json()) &&
           VerifyOffset(verifier, VT_LINE_REGIONS_JSON) &&
           verifier.VerifyString(line_regions_json()) &&
           VerifyField<uint8_t>(verifier, VT_SCHEDULE_ENABLED, 1) &&
           VerifyOffset(verifier, VT_SCHEDULE_START) &&
           verifier.VerifyString(schedule_start()) &&
           VerifyOffset(verifier, VT_SCHEDULE_END) &&
           verifier.VerifyString(schedule_end()) &&
           VerifyField<int32_t>(verifier, VT_SORT_ORDER, 4) &&
           VerifyOffset(verifier, VT_LABEL_MAPS) &&
           verifier.VerifyVector(label_maps()) &&
           verifier.VerifyVectorOfTables(label_maps()) &&
           verifier.EndTable();
  }
};

struct AlgoBindingBuilder {
  typedef AlgoBinding Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_algo_name(::flatbuffers::Offset<::flatbuffers::String> algo_name) {
    fbb_.AddOffset(AlgoBinding::VT_ALGO_NAME, algo_name);
  }
  void add_algo_version(::flatbuffers::Offset<::flatbuffers::String> algo_version) {
    fbb_.AddOffset(AlgoBinding::VT_ALGO_VERSION, algo_version);
  }
  void add_package_id(::flatbuffers::Offset<::flatbuffers::String> package_id) {
    fbb_.AddOffset(AlgoBinding::VT_PACKAGE_ID, package_id);
  }
  void add_so_path(::flatbuffers::Offset<::flatbuffers::String> so_path) {
    fbb_.AddOffset(AlgoBinding::VT_SO_PATH, so_path);
  }
  void add_algo_params_json(::flatbuffers::Offset<::flatbuffers::String> algo_params_json) {
    fbb_.AddOffset(AlgoBinding::VT_ALGO_PARAMS_JSON, algo_params_json);
  }
  void add_roi_regions_json(::flatbuffers::Offset<::flatbuffers::String> roi_regions_json) {
    fbb_.AddOffset(AlgoBinding::VT_ROI_REGIONS_JSON, roi_regions_json);
  }
  void add_mark_regions_json(::flatbuffers::Offset<::flatbuffers::String> mark_regions_json) {
    fbb_.AddOffset(AlgoBinding::VT_MARK_REGIONS_JSON, mark_regions_json);
  }
  void add_line_regions_json(::flatbuffers::Offset<::flatbuffers::String> line_regions_json) {
    fbb_.AddOffset(AlgoBinding::VT_LINE_REGIONS_JSON, line_regions_json);
  }
  void add_schedule_enabled(bool schedule_enabled) {
    fbb_.AddElement<uint8_t>(AlgoBinding::VT_SCHEDULE_ENABLED, static_cast<uint8_t>(schedule_enabled), 0);
  }
  void add_schedule_start(::flatbuffers::Offset<::flatbuffers::String> schedule_start) {
    fbb_.AddOffset(AlgoBinding::VT_SCHEDULE_START, schedule_start);
  }
  void add_schedule_end(::flatbuffers::Offset<::flatbuffers::String> schedule_end) {
    fbb_.AddOffset(AlgoBinding::VT_SCHEDULE_END, schedule_end);
  }
  void add_sort_order(int32_t sort_order) {
    fbb_.AddElement<int32_t>(AlgoBinding::VT_SORT_ORDER, sort_order, 0);
  }
  void add_label_maps(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>>> label_maps) {
    fbb_.AddOffset(AlgoBinding::VT_LABEL_MAPS, label_maps);
  }
  explicit AlgoBindingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AlgoBinding> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AlgoBinding>(end);
    fbb_.Required(o, AlgoBinding::VT_ALGO_NAME);
    fbb_.Required(o, AlgoBinding::VT_ALGO_VERSION);
    fbb_.Required(o, AlgoBinding::VT_PACKAGE_ID);
    fbb_.Required(o, AlgoBinding::VT_SO_PATH);
    return o;
  }
};

inline ::flatbuffers::Offset<AlgoBinding> CreateAlgoBinding(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> algo_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algo_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> package_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> so_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algo_params_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> roi_regions_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> mark_regions_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> line_regions_json = 0,
    bool schedule_enabled = false,
    ::flatbuffers::Offset<::flatbuffers::String> schedule_start = 0,
    ::flatbuffers::Offset<::flatbuffers::String> schedule_end = 0,
    int32_t sort_order = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>>> label_maps = 0) {
  AlgoBindingBuilder builder_(_fbb);
  builder_.add_label_maps(label_maps);
  builder_.add_sort_order(sort_order);
  builder_.add_schedule_end(schedule_end);
  builder_.add_schedule_start(schedule_start);
  builder_.add_line_regions_json(line_regions_json);
  builder_.add_mark_regions_json(mark_regions_json);
  builder_.add_roi_regions_json(roi_regions_json);
  builder_.add_algo_params_json(algo_params_json);
  builder_.add_so_path(so_path);
  builder_.add_package_id(package_id);
  builder_.add_algo_version(algo_version);
  builder_.add_algo_name(algo_name);
  builder_.add_schedule_enabled(schedule_enabled);
  return builder_.Finish();
}

struct AlgoBinding::Traits {
  using type = AlgoBinding;
  static auto constexpr Create = CreateAlgoBinding;
};

inline ::flatbuffers::Offset<AlgoBinding> CreateAlgoBindingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *algo_name = nullptr,
    const char *algo_version = nullptr,
    const char *package_id = nullptr,
    const char *so_path = nullptr,
    const char *algo_params_json = nullptr,
    const char *roi_regions_json = nullptr,
    const char *mark_regions_json = nullptr,
    const char *line_regions_json = nullptr,
    bool schedule_enabled = false,
    const char *schedule_start = nullptr,
    const char *schedule_end = nullptr,
    int32_t sort_order = 0,
    const std::vector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>> *label_maps = nullptr) {
  auto algo_name__ = algo_name ? _fbb.CreateString(algo_name) : 0;
  auto algo_version__ = algo_version ? _fbb.CreateString(algo_version) : 0;
  auto package_id__ = package_id ? _fbb.CreateString(package_id) : 0;
  auto so_path__ = so_path ? _fbb.CreateString(so_path) : 0;
  auto algo_params_json__ = algo_params_json ? _fbb.CreateString(algo_params_json) : 0;
  auto roi_regions_json__ = roi_regions_json ? _fbb.CreateString(roi_regions_json) : 0;
  auto mark_regions_json__ = mark_regions_json ? _fbb.CreateString(mark_regions_json) : 0;
  auto line_regions_json__ = line_regions_json ? _fbb.CreateString(line_regions_json) : 0;
  auto schedule_start__ = schedule_start ? _fbb.CreateString(schedule_start) : 0;
  auto schedule_end__ = schedule_end ? _fbb.CreateString(schedule_end) : 0;
  auto label_maps__ = label_maps ? _fbb.CreateVector<::flatbuffers::Offset<aivision::ipc::LabelMapEntry>>(*label_maps) : 0;
  return aivision::ipc::CreateAlgoBinding(
      _fbb,
      algo_name__,
      algo_version__,
      package_id__,
      so_path__,
      algo_params_json__,
      roi_regions_json__,
      mark_regions_json__,
      line_regions_json__,
      schedule_enabled,
      schedule_start__,
      schedule_end__,
      sort_order,
      label_maps__);
}

struct LabelMapEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LabelMapEntryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LABEL_ID = 4,
    VT_CATEGORY_CODE = 6,
    VT_DISPLAY_NAME = 8
  };
  int32_t label_id() const {
    return GetField<int32_t>(VT_LABEL_ID, 0);
  }
  int32_t category_code() const {
    return GetField<int32_t>(VT_CATEGORY_CODE, 0);
  }
  const ::flatbuffers::String *display_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPLAY_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_LABEL_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_CATEGORY_CODE, 4) &&
           VerifyOffset(verifier, VT_DISPLAY_NAME) &&
           verifier.VerifyString(display_name()) &&
           verifier.EndTable();
  }
};

struct LabelMapEntryBuilder {
  typedef LabelMapEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_label_id(int32_t label_id) {
    fbb_.AddElement<int32_t>(LabelMapEntry::VT_LABEL_ID, label_id, 0);
  }
  void add_category_code(int32_t category_code) {
    fbb_.AddElement<int32_t>(LabelMapEntry::VT_CATEGORY_CODE, category_code, 0);
  }
  void add_display_name(::flatbuffers::Offset<::flatbuffers::String> display_name) {
    fbb_.AddOffset(LabelMapEntry::VT_DISPLAY_NAME, display_name);
  }
  explicit LabelMapEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LabelMapEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LabelMapEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LabelMapEntry> CreateLabelMapEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t label_id = 0,
    int32_t category_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> display_name = 0) {
  LabelMapEntryBuilder builder_(_fbb);
  builder_.add_display_name(display_name);
  builder_.add_category_code(category_code);
  builder_.add_label_id(label_id);
  return builder_.Finish();
}

struct LabelMapEntry::Traits {
  using type = LabelMapEntry;
  static auto constexpr Create = CreateLabelMapEntry;
};

inline ::flatbuffers::Offset<LabelMapEntry> CreateLabelMapEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t label_id = 0,
    int32_t category_code = 0,
    const char *display_name = nullptr) {
  auto display_name__ = display_name ? _fbb.CreateString(display_name) : 0;
  return aivision::ipc::CreateLabelMapEntry(
      _fbb,
      label_id,
      category_code,
      display_name__);
}

/// 启动推理流指令 (SignalType.StartStream)
struct StartStreamCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartStreamCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASK_ID = 4,
    VT_STREAM_URL = 6,
    VT_DEVICE_ID = 8,
    VT_DEVICE_NAME = 10,
    VT_DECODE_HW_TYPE = 12,
    VT_MAX_RECONNECTS = 14,
    VT_RECONNECT_INTERVAL_SEC = 16,
    VT_ALGORITHMS = 18
  };
  const ::flatbuffers::String *task_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TASK_ID);
  }
  const ::flatbuffers::String *stream_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STREAM_URL);
  }
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  const ::flatbuffers::String *device_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_NAME);
  }
  aivision::ipc::DecodeHWType decode_hw_type() const {
    return static_cast<aivision::ipc::DecodeHWType>(GetField<int8_t>(VT_DECODE_HW_TYPE, 0));
  }
  int32_t max_reconnects() const {
    return GetField<int32_t>(VT_MAX_RECONNECTS, 3);
  }
  int32_t reconnect_interval_sec() const {
    return GetField<int32_t>(VT_RECONNECT_INTERVAL_SEC, 5);
  }
  /// 绑定的算法列表 (按 sort_order 串联执行)
  const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *algorithms() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *>(VT_ALGORITHMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TASK_ID) &&
           verifier.VerifyString(task_id()) &&
           VerifyOffsetRequired(verifier, VT_STREAM_URL) &&
           verifier.VerifyString(stream_url()) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           VerifyOffset(verifier, VT_DEVICE_NAME) &&
           verifier.VerifyString(device_name()) &&
           VerifyField<int8_t>(verifier, VT_DECODE_HW_TYPE, 1) &&
           VerifyField<int32_t>(verifier, VT_MAX_RECONNECTS, 4) &&
           VerifyField<int32_t>(verifier, VT_RECONNECT_INTERVAL_SEC, 4) &&
           VerifyOffset(verifier, VT_ALGORITHMS) &&
           verifier.VerifyVector(algorithms()) &&
           verifier.VerifyVectorOfTables(algorithms()) &&
           verifier.EndTable();
  }
};

struct StartStreamCmdBuilder {
  typedef StartStreamCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_task_id(::flatbuffers::Offset<::flatbuffers::String> task_id) {
    fbb_.AddOffset(StartStreamCmd::VT_TASK_ID, task_id);
  }
  void add_stream_url(::flatbuffers::Offset<::flatbuffers::String> stream_url) {
    fbb_.AddOffset(StartStreamCmd::VT_STREAM_URL, stream_url);
  }
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StartStreamCmd::VT_DEVICE_ID, device_id);
  }
  void add_device_name(::flatbuffers::Offset<::flatbuffers::String> device_name) {
    fbb_.AddOffset(StartStreamCmd::VT_DEVICE_NAME, device_name);
  }
  void add_decode_hw_type(aivision::ipc::DecodeHWType decode_hw_type) {
    fbb_.AddElement<int8_t>(StartStreamCmd::VT_DECODE_HW_TYPE, static_cast<int8_t>(decode_hw_type), 0);
  }
  void add_max_reconnects(int32_t max_reconnects) {
    fbb_.AddElement<int32_t>(StartStreamCmd::VT_MAX_RECONNECTS, max_reconnects, 3);
  }
  void add_reconnect_interval_sec(int32_t reconnect_interval_sec) {
    fbb_.AddElement<int32_t>(StartStreamCmd::VT_RECONNECT_INTERVAL_SEC, reconnect_interval_sec, 5);
  }
  void add_algorithms(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>> algorithms) {
    fbb_.AddOffset(StartStreamCmd::VT_ALGORITHMS, algorithms);
  }
  explicit StartStreamCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartStreamCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartStreamCmd>(end);
    fbb_.Required(o, StartStreamCmd::VT_TASK_ID);
    fbb_.Required(o, StartStreamCmd::VT_STREAM_URL);
    fbb_.Required(o, StartStreamCmd::VT_DEVICE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<StartStreamCmd> CreateStartStreamCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> task_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> stream_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> device_name = 0,
    aivision::ipc::DecodeHWType decode_hw_type = aivision::ipc::DecodeHWType::Auto,
    int32_t max_reconnects = 3,
    int32_t reconnect_interval_sec = 5,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>> algorithms = 0) {
  StartStreamCmdBuilder builder_(_fbb);
  builder_.add_algorithms(algorithms);
  builder_.add_reconnect_interval_sec(reconnect_interval_sec);
  builder_.add_max_reconnects(max_reconnects);
  builder_.add_device_name(device_name);
  builder_.add_device_id(device_id);
  builder_.add_stream_url(stream_url);
  builder_.add_task_id(task_id);
  builder_.add_decode_hw_type(decode_hw_type);
  return builder_.Finish();
}

struct StartStreamCmd::Traits {
  using type = StartStreamCmd;
  static auto constexpr Create = CreateStartStreamCmd;
};

inline ::flatbuffers::Offset<StartStreamCmd> CreateStartStreamCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *task_id = nullptr,
    const char *stream_url = nullptr,
    const char *device_id = nullptr,
    const char *device_name = nullptr,
    aivision::ipc::DecodeHWType decode_hw_type = aivision::ipc::DecodeHWType::Auto,
    int32_t max_reconnects = 3,
    int32_t reconnect_interval_sec = 5,
    const std::vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *algorithms = nullptr) {
  auto task_id__ = task_id ? _fbb.CreateString(task_id) : 0;
  auto stream_url__ = stream_url ? _fbb.CreateString(stream_url) : 0;
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  auto device_name__ = device_name ? _fbb.CreateString(device_name) : 0;
  auto algorithms__ = algorithms ? _fbb.CreateVector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>(*algorithms) : 0;
  return aivision::ipc::CreateStartStreamCmd(
      _fbb,
      task_id__,
      stream_url__,
      device_id__,
      device_name__,
      decode_hw_type,
      max_reconnects,
      reconnect_interval_sec,
      algorithms__);
}

/// 停止推理流指令 (SignalType.StopStream)
struct StopStreamCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopStreamCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASK_ID = 4,
    VT_REASON = 6
  };
  const ::flatbuffers::String *task_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TASK_ID);
  }
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TASK_ID) &&
           verifier.VerifyString(task_id()) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           verifier.EndTable();
  }
};

struct StopStreamCmdBuilder {
  typedef StopStreamCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_task_id(::flatbuffers::Offset<::flatbuffers::String> task_id) {
    fbb_.AddOffset(StopStreamCmd::VT_TASK_ID, task_id);
  }
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(StopStreamCmd::VT_REASON, reason);
  }
  explicit StopStreamCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopStreamCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopStreamCmd>(end);
    fbb_.Required(o, StopStreamCmd::VT_TASK_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<StopStreamCmd> CreateStopStreamCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> task_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0) {
  StopStreamCmdBuilder builder_(_fbb);
  builder_.add_reason(reason);
  builder_.add_task_id(task_id);
  return builder_.Finish();
}

struct StopStreamCmd::Traits {
  using type = StopStreamCmd;
  static auto constexpr Create = CreateStopStreamCmd;
};

inline ::flatbuffers::Offset<StopStreamCmd> CreateStopStreamCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *task_id = nullptr,
    const char *reason = nullptr) {
  auto task_id__ = task_id ? _fbb.CreateString(task_id) : 0;
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return aivision::ipc::CreateStopStreamCmd(
      _fbb,
      task_id__,
      reason__);
}

/// 更新算法配置指令 (SignalType.UpdateAlgoConfig)
/// 配置变更会触发热更新流程 (状态机)
struct UpdateAlgoConfigCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateAlgoConfigCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASK_ID = 4,
    VT_ALGO_NAME = 6,
    VT_ALGO_VERSION = 8,
    VT_PACKAGE_ID = 10,
    VT_SO_PATH = 12,
    VT_ALGO_PARAMS_JSON = 14,
    VT_ROI_REGIONS_JSON = 16,
    VT_MARK_REGIONS_JSON = 18,
    VT_LINE_REGIONS_JSON = 20
  };
  const ::flatbuffers::String *task_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TASK_ID);
  }
  const ::flatbuffers::String *algo_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_NAME);
  }
  const ::flatbuffers::String *algo_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_VERSION);
  }
  const ::flatbuffers::String *package_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PACKAGE_ID);
  }
  const ::flatbuffers::String *so_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SO_PATH);
  }
  /// 新的算法参数 (JSON 透传)
  const ::flatbuffers::String *algo_params_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGO_PARAMS_JSON);
  }
  /// 新的 ROI/MARK/LINE 区域 (JSON 透传)
  const ::flatbuffers::String *roi_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROI_REGIONS_JSON);
  }
  const ::flatbuffers::String *mark_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MARK_REGIONS_JSON);
  }
  const ::flatbuffers::String *line_regions_json() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LINE_REGIONS_JSON);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TASK_ID) &&
           verifier.VerifyString(task_id()) &&
           VerifyOffsetRequired(verifier, VT_ALGO_NAME) &&
           verifier.VerifyString(algo_name()) &&
           VerifyOffsetRequired(verifier, VT_ALGO_VERSION) &&
           verifier.VerifyString(algo_version()) &&
           VerifyOffsetRequired(verifier, VT_PACKAGE_ID) &&
           verifier.VerifyString(package_id()) &&
           VerifyOffsetRequired(verifier, VT_SO_PATH) &&
           verifier.VerifyString(so_path()) &&
           VerifyOffset(verifier, VT_ALGO_PARAMS_JSON) &&
           verifier.VerifyString(algo_params_json()) &&
           VerifyOffset(verifier, VT_ROI_REGIONS_JSON) &&
           verifier.VerifyString(roi_regions_json()) &&
           VerifyOffset(verifier, VT_MARK_REGIONS_JSON) &&
           verifier.VerifyString(mark_regions_json()) &&
           VerifyOffset(verifier, VT_LINE_REGIONS_JSON) &&
           verifier.VerifyString(line_regions_json()) &&
           verifier.EndTable();
  }
};

struct UpdateAlgoConfigCmdBuilder {
  typedef UpdateAlgoConfigCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_task_id(::flatbuffers::Offset<::flatbuffers::String> task_id) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_TASK_ID, task_id);
  }
  void add_algo_name(::flatbuffers::Offset<::flatbuffers::String> algo_name) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_ALGO_NAME, algo_name);
  }
  void add_algo_version(::flatbuffers::Offset<::flatbuffers::String> algo_version) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_ALGO_VERSION, algo_version);
  }
  void add_package_id(::flatbuffers::Offset<::flatbuffers::String> package_id) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_PACKAGE_ID, package_id);
  }
  void add_so_path(::flatbuffers::Offset<::flatbuffers::String> so_path) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_SO_PATH, so_path);
  }
  void add_algo_params_json(::flatbuffers::Offset<::flatbuffers::String> algo_params_json) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_ALGO_PARAMS_JSON, algo_params_json);
  }
  void add_roi_regions_json(::flatbuffers::Offset<::flatbuffers::String> roi_regions_json) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_ROI_REGIONS_JSON, roi_regions_json);
  }
  void add_mark_regions_json(::flatbuffers::Offset<::flatbuffers::String> mark_regions_json) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_MARK_REGIONS_JSON, mark_regions_json);
  }
  void add_line_regions_json(::flatbuffers::Offset<::flatbuffers::String> line_regions_json) {
    fbb_.AddOffset(UpdateAlgoConfigCmd::VT_LINE_REGIONS_JSON, line_regions_json);
  }
  explicit UpdateAlgoConfigCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateAlgoConfigCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateAlgoConfigCmd>(end);
    fbb_.Required(o, UpdateAlgoConfigCmd::VT_TASK_ID);
    fbb_.Required(o, UpdateAlgoConfigCmd::VT_ALGO_NAME);
    fbb_.Required(o, UpdateAlgoConfigCmd::VT_ALGO_VERSION);
    fbb_.Required(o, UpdateAlgoConfigCmd::VT_PACKAGE_ID);
    fbb_.Required(o, UpdateAlgoConfigCmd::VT_SO_PATH);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateAlgoConfigCmd> CreateUpdateAlgoConfigCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> task_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algo_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algo_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> package_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> so_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algo_params_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> roi_regions_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> mark_regions_json = 0,
    ::flatbuffers::Offset<::flatbuffers::String> line_regions_json = 0) {
  UpdateAlgoConfigCmdBuilder builder_(_fbb);
  builder_.add_line_regions_json(line_regions_json);
  builder_.add_mark_regions_json(mark_regions_json);
  builder_.add_roi_regions_json(roi_regions_json);
  builder_.add_algo_params_json(algo_params_json);
  builder_.add_so_path(so_path);
  builder_.add_package_id(package_id);
  builder_.add_algo_version(algo_version);
  builder_.add_algo_name(algo_name);
  builder_.add_task_id(task_id);
  return builder_.Finish();
}

struct UpdateAlgoConfigCmd::Traits {
  using type = UpdateAlgoConfigCmd;
  static auto constexpr Create = CreateUpdateAlgoConfigCmd;
};

inline ::flatbuffers::Offset<UpdateAlgoConfigCmd> CreateUpdateAlgoConfigCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *task_id = nullptr,
    const char *algo_name = nullptr,
    const char *algo_version = nullptr,
    const char *package_id = nullptr,
    const char *so_path = nullptr,
    const char *algo_params_json = nullptr,
    const char *roi_regions_json = nullptr,
    const char *mark_regions_json = nullptr,
    const char *line_regions_json = nullptr) {
  auto task_id__ = task_id ? _fbb.CreateString(task_id) : 0;
  auto algo_name__ = algo_name ? _fbb.CreateString(algo_name) : 0;
  auto algo_version__ = algo_version ? _fbb.CreateString(algo_version) : 0;
  auto package_id__ = package_id ? _fbb.CreateString(package_id) : 0;
  auto so_path__ = so_path ? _fbb.CreateString(so_path) : 0;
  auto algo_params_json__ = algo_params_json ? _fbb.CreateString(algo_params_json) : 0;
  auto roi_regions_json__ = roi_regions_json ? _fbb.CreateString(roi_regions_json) : 0;
  auto mark_regions_json__ = mark_regions_json ? _fbb.CreateString(mark_regions_json) : 0;
  auto line_regions_json__ = line_regions_json ? _fbb.CreateString(line_regions_json) : 0;
  return aivision::ipc::CreateUpdateAlgoConfigCmd(
      _fbb,
      task_id__,
      algo_name__,
      algo_version__,
      package_id__,
      so_path__,
      algo_params_json__,
      roi_regions_json__,
      mark_regions_json__,
      line_regions_json__);
}

/// 更新流配置指令 (SignalType.UpdateStreamConfig)
struct UpdateStreamConfigCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateStreamConfigCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TASK_ID = 4,
    VT_MAX_RECONNECTS = 6,
    VT_RECONNECT_INTERVAL_SEC = 8
  };
  const ::flatbuffers::String *task_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TASK_ID);
  }
  int32_t max_reconnects() const {
    return GetField<int32_t>(VT_MAX_RECONNECTS, 0);
  }
  int32_t reconnect_interval_sec() const {
    return GetField<int32_t>(VT_RECONNECT_INTERVAL_SEC, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TASK_ID) &&
           verifier.VerifyString(task_id()) &&
           VerifyField<int32_t>(verifier, VT_MAX_RECONNECTS, 4) &&
           VerifyField<int32_t>(verifier, VT_RECONNECT_INTERVAL_SEC, 4) &&
           verifier.EndTable();
  }
};

struct UpdateStreamConfigCmdBuilder {
  typedef UpdateStreamConfigCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_task_id(::flatbuffers::Offset<::flatbuffers::String> task_id) {
    fbb_.AddOffset(UpdateStreamConfigCmd::VT_TASK_ID, task_id);
  }
  void add_max_reconnects(int32_t max_reconnects) {
    fbb_.AddElement<int32_t>(UpdateStreamConfigCmd::VT_MAX_RECONNECTS, max_reconnects, 0);
  }
  void add_reconnect_interval_sec(int32_t reconnect_interval_sec) {
    fbb_.AddElement<int32_t>(UpdateStreamConfigCmd::VT_RECONNECT_INTERVAL_SEC, reconnect_interval_sec, 0);
  }
  explicit UpdateStreamConfigCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UpdateStreamConfigCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UpdateStreamConfigCmd>(end);
    fbb_.Required(o, UpdateStreamConfigCmd::VT_TASK_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<UpdateStreamConfigCmd> CreateUpdateStreamConfigCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> task_id = 0,
    int32_t max_reconnects = 0,
    int32_t reconnect_interval_sec = 0) {
  UpdateStreamConfigCmdBuilder builder_(_fbb);
  builder_.add_reconnect_interval_sec(reconnect_interval_sec);
  builder_.add_max_reconnects(max_reconnects);
  builder_.add_task_id(task_id);
  return builder_.Finish();
}

struct UpdateStreamConfigCmd::Traits {
  using type = UpdateStreamConfigCmd;
  static auto constexpr Create = CreateUpdateStreamConfigCmd;
};

inline ::flatbuffers::Offset<UpdateStreamConfigCmd> CreateUpdateStreamConfigCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *task_id = nullptr,
    int32_t max_reconnects = 0,
    int32_t reconnect_interval_sec = 0) {
  auto task_id__ = task_id ? _fbb.CreateString(task_id) : 0;
  return aivision::ipc::CreateUpdateStreamConfigCmd(
      _fbb,
      task_id__,
      max_reconnects,
      reconnect_interval_sec);
}

/// 心跳指令 (SignalType.Heartbeat)
struct HeartbeatCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQUENCE = 4
  };
  uint64_t sequence() const {
    return GetField<uint64_t>(VT_SEQUENCE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SEQUENCE, 8) &&
           verifier.EndTable();
  }
};

struct HeartbeatCmdBuilder {
  typedef HeartbeatCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sequence(uint64_t sequence) {
    fbb_.AddElement<uint64_t>(HeartbeatCmd::VT_SEQUENCE, sequence, 0);
  }
  explicit HeartbeatCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HeartbeatCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HeartbeatCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HeartbeatCmd> CreateHeartbeatCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t sequence = 0) {
  HeartbeatCmdBuilder builder_(_fbb);
  builder_.add_sequence(sequence);
  return builder_.Finish();
}

struct HeartbeatCmd::Traits {
  using type = HeartbeatCmd;
  static auto constexpr Create = CreateHeartbeatCmd;
};

/// 关闭引擎指令 (SignalType.Shutdown)
struct ShutdownCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShutdownCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4,
    VT_GRACEFUL_TIMEOUT_SEC = 6
  };
  const ::flatbuffers::String *reason() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON);
  }
  /// 优雅关闭超时 (秒)
  uint32_t graceful_timeout_sec() const {
    return GetField<uint32_t>(VT_GRACEFUL_TIMEOUT_SEC, 30);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           VerifyField<uint32_t>(verifier, VT_GRACEFUL_TIMEOUT_SEC, 4) &&
           verifier.EndTable();
  }
};

struct ShutdownCmdBuilder {
  typedef ShutdownCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(::flatbuffers::Offset<::flatbuffers::String> reason) {
    fbb_.AddOffset(ShutdownCmd::VT_REASON, reason);
  }
  void add_graceful_timeout_sec(uint32_t graceful_timeout_sec) {
    fbb_.AddElement<uint32_t>(ShutdownCmd::VT_GRACEFUL_TIMEOUT_SEC, graceful_timeout_sec, 30);
  }
  explicit ShutdownCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShutdownCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShutdownCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShutdownCmd> CreateShutdownCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> reason = 0,
    uint32_t graceful_timeout_sec = 30) {
  ShutdownCmdBuilder builder_(_fbb);
  builder_.add_graceful_timeout_sec(graceful_timeout_sec);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct ShutdownCmd::Traits {
  using type = ShutdownCmd;
  static auto constexpr Create = CreateShutdownCmd;
};

inline ::flatbuffers::Offset<ShutdownCmd> CreateShutdownCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *reason = nullptr,
    uint32_t graceful_timeout_sec = 30) {
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return aivision::ipc::CreateShutdownCmd(
      _fbb,
      reason__,
      graceful_timeout_sec);
}

/// 启动流指令 (SignalType.StreamStart)
struct StreamStartCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamStartCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_ID = 4,
    VT_STREAM_URL = 6,
    VT_ENABLE_INFER = 8,
    VT_ENABLE_PLAYBACK = 10,
    VT_PLAYBACK_URL = 12,
    VT_ALGORITHMS = 14
  };
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  const ::flatbuffers::String *stream_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STREAM_URL);
  }
  bool enable_infer() const {
    return GetField<uint8_t>(VT_ENABLE_INFER, 1) != 0;
  }
  bool enable_playback() const {
    return GetField<uint8_t>(VT_ENABLE_PLAYBACK, 0) != 0;
  }
  const ::flatbuffers::String *playback_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PLAYBACK_URL);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *algorithms() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *>(VT_ALGORITHMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           VerifyOffsetRequired(verifier, VT_STREAM_URL) &&
           verifier.VerifyString(stream_url()) &&
           VerifyField<uint8_t>(verifier, VT_ENABLE_INFER, 1) &&
           VerifyField<uint8_t>(verifier, VT_ENABLE_PLAYBACK, 1) &&
           VerifyOffset(verifier, VT_PLAYBACK_URL) &&
           verifier.VerifyString(playback_url()) &&
           VerifyOffset(verifier, VT_ALGORITHMS) &&
           verifier.VerifyVector(algorithms()) &&
           verifier.VerifyVectorOfTables(algorithms()) &&
           verifier.EndTable();
  }
};

struct StreamStartCmdBuilder {
  typedef StreamStartCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StreamStartCmd::VT_DEVICE_ID, device_id);
  }
  void add_stream_url(::flatbuffers::Offset<::flatbuffers::String> stream_url) {
    fbb_.AddOffset(StreamStartCmd::VT_STREAM_URL, stream_url);
  }
  void add_enable_infer(bool enable_infer) {
    fbb_.AddElement<uint8_t>(StreamStartCmd::VT_ENABLE_INFER, static_cast<uint8_t>(enable_infer), 1);
  }
  void add_enable_playback(bool enable_playback) {
    fbb_.AddElement<uint8_t>(StreamStartCmd::VT_ENABLE_PLAYBACK, static_cast<uint8_t>(enable_playback), 0);
  }
  void add_playback_url(::flatbuffers::Offset<::flatbuffers::String> playback_url) {
    fbb_.AddOffset(StreamStartCmd::VT_PLAYBACK_URL, playback_url);
  }
  void add_algorithms(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>> algorithms) {
    fbb_.AddOffset(StreamStartCmd::VT_ALGORITHMS, algorithms);
  }
  explicit StreamStartCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamStartCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamStartCmd>(end);
    fbb_.Required(o, StreamStartCmd::VT_DEVICE_ID);
    fbb_.Required(o, StreamStartCmd::VT_STREAM_URL);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamStartCmd> CreateStreamStartCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> stream_url = 0,
    bool enable_infer = true,
    bool enable_playback = false,
    ::flatbuffers::Offset<::flatbuffers::String> playback_url = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>> algorithms = 0) {
  StreamStartCmdBuilder builder_(_fbb);
  builder_.add_algorithms(algorithms);
  builder_.add_playback_url(playback_url);
  builder_.add_stream_url(stream_url);
  builder_.add_device_id(device_id);
  builder_.add_enable_playback(enable_playback);
  builder_.add_enable_infer(enable_infer);
  return builder_.Finish();
}

struct StreamStartCmd::Traits {
  using type = StreamStartCmd;
  static auto constexpr Create = CreateStreamStartCmd;
};

inline ::flatbuffers::Offset<StreamStartCmd> CreateStreamStartCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_id = nullptr,
    const char *stream_url = nullptr,
    bool enable_infer = true,
    bool enable_playback = false,
    const char *playback_url = nullptr,
    const std::vector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>> *algorithms = nullptr) {
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  auto stream_url__ = stream_url ? _fbb.CreateString(stream_url) : 0;
  auto playback_url__ = playback_url ? _fbb.CreateString(playback_url) : 0;
  auto algorithms__ = algorithms ? _fbb.CreateVector<::flatbuffers::Offset<aivision::ipc::AlgoBinding>>(*algorithms) : 0;
  return aivision::ipc::CreateStreamStartCmd(
      _fbb,
      device_id__,
      stream_url__,
      enable_infer,
      enable_playback,
      playback_url__,
      algorithms__);
}

/// 停止流指令 (SignalType.StreamStop)
struct StreamStopCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamStopCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_ID = 4
  };
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           verifier.EndTable();
  }
};

struct StreamStopCmdBuilder {
  typedef StreamStopCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StreamStopCmd::VT_DEVICE_ID, device_id);
  }
  explicit StreamStopCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamStopCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamStopCmd>(end);
    fbb_.Required(o, StreamStopCmd::VT_DEVICE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamStopCmd> CreateStreamStopCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0) {
  StreamStopCmdBuilder builder_(_fbb);
  builder_.add_device_id(device_id);
  return builder_.Finish();
}

struct StreamStopCmd::Traits {
  using type = StreamStopCmd;
  static auto constexpr Create = CreateStreamStopCmd;
};

inline ::flatbuffers::Offset<StreamStopCmd> CreateStreamStopCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_id = nullptr) {
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  return aivision::ipc::CreateStreamStopCmd(
      _fbb,
      device_id__);
}

/// 启动播放指令 (SignalType.StreamPlaybackStart)
struct StreamPlaybackStartCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamPlaybackStartCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_ID = 4
  };
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           verifier.EndTable();
  }
};

struct StreamPlaybackStartCmdBuilder {
  typedef StreamPlaybackStartCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StreamPlaybackStartCmd::VT_DEVICE_ID, device_id);
  }
  explicit StreamPlaybackStartCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamPlaybackStartCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamPlaybackStartCmd>(end);
    fbb_.Required(o, StreamPlaybackStartCmd::VT_DEVICE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamPlaybackStartCmd> CreateStreamPlaybackStartCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0) {
  StreamPlaybackStartCmdBuilder builder_(_fbb);
  builder_.add_device_id(device_id);
  return builder_.Finish();
}

struct StreamPlaybackStartCmd::Traits {
  using type = StreamPlaybackStartCmd;
  static auto constexpr Create = CreateStreamPlaybackStartCmd;
};

inline ::flatbuffers::Offset<StreamPlaybackStartCmd> CreateStreamPlaybackStartCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_id = nullptr) {
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  return aivision::ipc::CreateStreamPlaybackStartCmd(
      _fbb,
      device_id__);
}

/// 停止播放指令 (SignalType.StreamPlaybackStop)
struct StreamPlaybackStopCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamPlaybackStopCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_ID = 4
  };
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           verifier.EndTable();
  }
};

struct StreamPlaybackStopCmdBuilder {
  typedef StreamPlaybackStopCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StreamPlaybackStopCmd::VT_DEVICE_ID, device_id);
  }
  explicit StreamPlaybackStopCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamPlaybackStopCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamPlaybackStopCmd>(end);
    fbb_.Required(o, StreamPlaybackStopCmd::VT_DEVICE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamPlaybackStopCmd> CreateStreamPlaybackStopCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0) {
  StreamPlaybackStopCmdBuilder builder_(_fbb);
  builder_.add_device_id(device_id);
  return builder_.Finish();
}

struct StreamPlaybackStopCmd::Traits {
  using type = StreamPlaybackStopCmd;
  static auto constexpr Create = CreateStreamPlaybackStopCmd;
};

inline ::flatbuffers::Offset<StreamPlaybackStopCmd> CreateStreamPlaybackStopCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_id = nullptr) {
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  return aivision::ipc::CreateStreamPlaybackStopCmd(
      _fbb,
      device_id__);
}

/// 流状态查询 (SignalType.StreamStatus)
struct StreamStatusCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamStatusCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICE_ID = 4
  };
  const ::flatbuffers::String *device_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DEVICE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DEVICE_ID) &&
           verifier.VerifyString(device_id()) &&
           verifier.EndTable();
  }
};

struct StreamStatusCmdBuilder {
  typedef StreamStatusCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_device_id(::flatbuffers::Offset<::flatbuffers::String> device_id) {
    fbb_.AddOffset(StreamStatusCmd::VT_DEVICE_ID, device_id);
  }
  explicit StreamStatusCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamStatusCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamStatusCmd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamStatusCmd> CreateStreamStatusCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> device_id = 0) {
  StreamStatusCmdBuilder builder_(_fbb);
  builder_.add_device_id(device_id);
  return builder_.Finish();
}

struct StreamStatusCmd::Traits {
  using type = StreamStatusCmd;
  static auto constexpr Create = CreateStreamStatusCmd;
};

inline ::flatbuffers::Offset<StreamStatusCmd> CreateStreamStatusCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *device_id = nullptr) {
  auto device_id__ = device_id ? _fbb.CreateString(device_id) : 0;
  return aivision::ipc::CreateStreamStatusCmd(
      _fbb,
      device_id__);
}

/// 启动自检指令 (SignalType.StartSelfCheck)
struct StartSelfCheckCmd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartSelfCheckCmdBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DOWNLOAD_URL = 4,
    VT_TOKEN = 6,
    VT_ALGORITHM_NAME = 8,
    VT_VERSION = 10
  };
  const ::flatbuffers::String *download_url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DOWNLOAD_URL);
  }
  const ::flatbuffers::String *token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOKEN);
  }
  const ::flatbuffers::String *algorithm_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALGORITHM_NAME);
  }
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DOWNLOAD_URL) &&
           verifier.VerifyString(download_url()) &&
           VerifyOffsetRequired(verifier, VT_TOKEN) &&
           verifier.VerifyString(token()) &&
           VerifyOffsetRequired(verifier, VT_ALGORITHM_NAME) &&
           verifier.VerifyString(algorithm_name()) &&
           VerifyOffsetRequired(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           verifier.EndTable();
  }
};

struct StartSelfCheckCmdBuilder {
  typedef StartSelfCheckCmd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_download_url(::flatbuffers::Offset<::flatbuffers::String> download_url) {
    fbb_.AddOffset(StartSelfCheckCmd::VT_DOWNLOAD_URL, download_url);
  }
  void add_token(::flatbuffers::Offset<::flatbuffers::String> token) {
    fbb_.AddOffset(StartSelfCheckCmd::VT_TOKEN, token);
  }
  void add_algorithm_name(::flatbuffers::Offset<::flatbuffers::String> algorithm_name) {
    fbb_.AddOffset(StartSelfCheckCmd::VT_ALGORITHM_NAME, algorithm_name);
  }
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(StartSelfCheckCmd::VT_VERSION, version);
  }
  explicit StartSelfCheckCmdBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartSelfCheckCmd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartSelfCheckCmd>(end);
    fbb_.Required(o, StartSelfCheckCmd::VT_DOWNLOAD_URL);
    fbb_.Required(o, StartSelfCheckCmd::VT_TOKEN);
    fbb_.Required(o, StartSelfCheckCmd::VT_ALGORITHM_NAME);
    fbb_.Required(o, StartSelfCheckCmd::VT_VERSION);
    return o;
  }
};

inline ::flatbuffers::Offset<StartSelfCheckCmd> CreateStartSelfCheckCmd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> download_url = 0,
    ::flatbuffers::Offset<::flatbuffers::String> token = 0,
    ::flatbuffers::Offset<::flatbuffers::String> algorithm_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0) {
  StartSelfCheckCmdBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_algorithm_name(algorithm_name);
  builder_.add_token(token);
  builder_.add_download_url(download_url);
  return builder_.Finish();
}

struct StartSelfCheckCmd::Traits {
  using type = StartSelfCheckCmd;
  static auto constexpr Create = CreateStartSelfCheckCmd;
};

inline ::flatbuffers::Offset<StartSelfCheckCmd> CreateStartSelfCheckCmdDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *download_url = nullptr,
    const char *token = nullptr,
    const char *algorithm_name = nullptr,
    const char *version = nullptr) {
  auto download_url__ = download_url ? _fbb.CreateString(download_url) : 0;
  auto token__ = token ? _fbb.CreateString(token) : 0;
  auto algorithm_name__ = algorithm_name ? _fbb.CreateString(algorithm_name) : 0;
  auto version__ = version ? _fbb.CreateString(version) : 0;
  return aivision::ipc::CreateStartSelfCheckCmd(
      _fbb,
      download_url__,
      token__,
      algorithm_name__,
      version__);
}

inline const aivision::ipc::StartSelfCheckCmd *GetStartSelfCheckCmd(const void *buf) {
  return ::flatbuffers::GetRoot<aivision::ipc::StartSelfCheckCmd>(buf);
}

inline const aivision::ipc::StartSelfCheckCmd *GetSizePrefixedStartSelfCheckCmd(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<aivision::ipc::StartSelfCheckCmd>(buf);
}

template <bool B = false>
inline bool VerifyStartSelfCheckCmdBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<aivision::ipc::StartSelfCheckCmd>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedStartSelfCheckCmdBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<aivision::ipc::StartSelfCheckCmd>(nullptr);
}

inline void FinishStartSelfCheckCmdBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<aivision::ipc::StartSelfCheckCmd> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStartSelfCheckCmdBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<aivision::ipc::StartSelfCheckCmd> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ipc
}  // namespace aivision

#endif  // FLATBUFFERS_GENERATED_COMMANDS_AIVISION_IPC_H_
