// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENVELOPE_AIVISION_IPC_H_
#define FLATBUFFERS_GENERATED_ENVELOPE_AIVISION_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace aivision {
namespace ipc {

struct IPCEnvelope;
struct IPCEnvelopeBuilder;

/// 信令类型枚举：区分每个消息的 payload 类型
enum class SignalType : uint16_t {
  Unknown = 0,
  StartStream = 256,
  StopStream = 257,
  UpdateAlgoConfig = 258,
  UpdateStreamConfig = 259,
  Heartbeat = 260,
  StartSelfCheck = 261,
  Shutdown = 511,
  InferenceResult = 512,
  StreamStatusReport = 513,
  AlgoLoadResult = 514,
  EngineMetrics = 515,
  HeartbeatAck = 516,
  Error = 768,
  Log = 769,
  MIN = Unknown,
  MAX = Log
};

inline const SignalType (&EnumValuesSignalType())[15] {
  static const SignalType values[] = {
    SignalType::Unknown,
    SignalType::StartStream,
    SignalType::StopStream,
    SignalType::UpdateAlgoConfig,
    SignalType::UpdateStreamConfig,
    SignalType::Heartbeat,
    SignalType::StartSelfCheck,
    SignalType::Shutdown,
    SignalType::InferenceResult,
    SignalType::StreamStatusReport,
    SignalType::AlgoLoadResult,
    SignalType::EngineMetrics,
    SignalType::HeartbeatAck,
    SignalType::Error,
    SignalType::Log
  };
  return values;
}

inline const char *EnumNameSignalType(SignalType e) {
  switch (e) {
    case SignalType::Unknown: return "Unknown";
    case SignalType::StartStream: return "StartStream";
    case SignalType::StopStream: return "StopStream";
    case SignalType::UpdateAlgoConfig: return "UpdateAlgoConfig";
    case SignalType::UpdateStreamConfig: return "UpdateStreamConfig";
    case SignalType::Heartbeat: return "Heartbeat";
    case SignalType::StartSelfCheck: return "StartSelfCheck";
    case SignalType::Shutdown: return "Shutdown";
    case SignalType::InferenceResult: return "InferenceResult";
    case SignalType::StreamStatusReport: return "StreamStatusReport";
    case SignalType::AlgoLoadResult: return "AlgoLoadResult";
    case SignalType::EngineMetrics: return "EngineMetrics";
    case SignalType::HeartbeatAck: return "HeartbeatAck";
    case SignalType::Error: return "Error";
    case SignalType::Log: return "Log";
    default: return "";
  }
}

/// IPC 信封：所有消息的最外层包装
struct IPCEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IPCEnvelopeBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_SIGNAL_TYPE = 6,
    VT_SEQUENCE_ID = 8,
    VT_TIMESTAMP_NS = 10,
    VT_PAYLOAD_TYPE = 12,
    VT_PAYLOAD = 14
  };
  /// Schema 版本号 (major*100 + minor)
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 100);
  }
  /// 信令类型
  aivision::ipc::SignalType signal_type() const {
    return static_cast<aivision::ipc::SignalType>(GetField<uint16_t>(VT_SIGNAL_TYPE, 0));
  }
  /// 消息序列号 (请求-响应配对)
  uint64_t sequence_id() const {
    return GetField<uint64_t>(VT_SEQUENCE_ID, 0);
  }
  /// 发送时间戳 (Unix 纳秒)
  uint64_t timestamp_ns() const {
    return GetField<uint64_t>(VT_TIMESTAMP_NS, 0);
  }
  /// Payload 类型标识 (反射用)
  const ::flatbuffers::String *payload_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD_TYPE);
  }
  /// 实际消息体 (指向具体 table 的 root)
  const ::flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyField<uint16_t>(verifier, VT_SIGNAL_TYPE, 2) &&
           VerifyField<uint64_t>(verifier, VT_SEQUENCE_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP_NS, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD_TYPE) &&
           verifier.VerifyString(payload_type()) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
};

struct IPCEnvelopeBuilder {
  typedef IPCEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(IPCEnvelope::VT_SCHEMA_VERSION, schema_version, 100);
  }
  void add_signal_type(aivision::ipc::SignalType signal_type) {
    fbb_.AddElement<uint16_t>(IPCEnvelope::VT_SIGNAL_TYPE, static_cast<uint16_t>(signal_type), 0);
  }
  void add_sequence_id(uint64_t sequence_id) {
    fbb_.AddElement<uint64_t>(IPCEnvelope::VT_SEQUENCE_ID, sequence_id, 0);
  }
  void add_timestamp_ns(uint64_t timestamp_ns) {
    fbb_.AddElement<uint64_t>(IPCEnvelope::VT_TIMESTAMP_NS, timestamp_ns, 0);
  }
  void add_payload_type(::flatbuffers::Offset<::flatbuffers::String> payload_type) {
    fbb_.AddOffset(IPCEnvelope::VT_PAYLOAD_TYPE, payload_type);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(IPCEnvelope::VT_PAYLOAD, payload);
  }
  explicit IPCEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IPCEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IPCEnvelope>(end);
    fbb_.Required(o, IPCEnvelope::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<IPCEnvelope> CreateIPCEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 100,
    aivision::ipc::SignalType signal_type = aivision::ipc::SignalType::Unknown,
    uint64_t sequence_id = 0,
    uint64_t timestamp_ns = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload = 0) {
  IPCEnvelopeBuilder builder_(_fbb);
  builder_.add_timestamp_ns(timestamp_ns);
  builder_.add_sequence_id(sequence_id);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  builder_.add_schema_version(schema_version);
  builder_.add_signal_type(signal_type);
  return builder_.Finish();
}

struct IPCEnvelope::Traits {
  using type = IPCEnvelope;
  static auto constexpr Create = CreateIPCEnvelope;
};

inline ::flatbuffers::Offset<IPCEnvelope> CreateIPCEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 100,
    aivision::ipc::SignalType signal_type = aivision::ipc::SignalType::Unknown,
    uint64_t sequence_id = 0,
    uint64_t timestamp_ns = 0,
    const char *payload_type = nullptr,
    const std::vector<uint8_t> *payload = nullptr) {
  auto payload_type__ = payload_type ? _fbb.CreateString(payload_type) : 0;
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return aivision::ipc::CreateIPCEnvelope(
      _fbb,
      schema_version,
      signal_type,
      sequence_id,
      timestamp_ns,
      payload_type__,
      payload__);
}

inline const aivision::ipc::IPCEnvelope *GetIPCEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<aivision::ipc::IPCEnvelope>(buf);
}

inline const aivision::ipc::IPCEnvelope *GetSizePrefixedIPCEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<aivision::ipc::IPCEnvelope>(buf);
}

template <bool B = false>
inline bool VerifyIPCEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<aivision::ipc::IPCEnvelope>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedIPCEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<aivision::ipc::IPCEnvelope>(nullptr);
}

inline void FinishIPCEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<aivision::ipc::IPCEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedIPCEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<aivision::ipc::IPCEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ipc
}  // namespace aivision

#endif  // FLATBUFFERS_GENERATED_ENVELOPE_AIVISION_IPC_H_
