// Code generated by niko-admin. DO NOT EDIT.
// Route configurations
// Generate at: 2026-05-16

import { RouteConfig } from './types';

/**
 * 管理后台路由配置
 * 注意：icon 使用 react-icons 的图标名称（如 'MdHome', 'MdPerson'）
 * 在 sidebar 中会动态映射到对应的图标组件
 */
export const adminRoutes: RouteConfig[] = [
  {
    id: 'dashboard',
    path: '/default',
    i18nKey: 'menu:dashboard',
    icon: 'MdHome',
    component: () => import('../views/admin/default'),
    layout: '/admin',
  },
  {
    id: 'smart-records',
    path: '/smart-records',
    i18nKey: 'menu:smart-records',
    icon: 'MdNotificationsActive',
    component: () => import('../views/admin/smart-records'),
    layout: '/admin',
  },
  {
    id: 'media-management',
    path: '/media-management',
    i18nKey: 'menu:media-management',
    icon: 'MdLiveTv',
    layout: '/admin',
    children: [
      {
        id: 'live-view',
        path: '/media/live',
        i18nKey: 'menu:live-view',
        icon: 'MdViewStream',
        component: () => import('../views/admin/media/MediaDashboard'),
        layout: '/admin',
      },
      {
        id: 'stream-status',
        path: '/media/streams',
        i18nKey: 'menu:stream-status',
        icon: 'MdTimeline',
        component: () => import('../views/admin/media/stream-status'),
        layout: '/admin',
      },
      {
        id: 'recordings',
        path: '/media/recordings',
        i18nKey: 'menu:recordings',
        icon: 'MdVideoLibrary',
        component: () => import('../views/admin/media/RecordingsView'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'aivision',
    path: '/aivision',
    i18nKey: 'menu:aivision',
    icon: 'MdVisibility',
    layout: '/admin',
    children: [
      {
        id: 'aivisiontasks',
        path: '/aivision/tasks',
        i18nKey: 'menu:aivisiontasks',
        icon: 'MdAssignment',
        component: () => import('../views/admin/ai-tasks'),
        layout: '/admin',
      },
      {
        id: 'ai-time-schedules',
        path: '/aivision/time-schedules',
        i18nKey: 'menu:ai-time-schedules',
        icon: 'MdSchedule',
        component: () => import('../views/admin/ai-time-schedules'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'device-management',
    path: '/device-management',
    i18nKey: 'menu:device-management',
    icon: 'MdVideocam',
    layout: '/admin',
    children: [
      {
        id: 'devices',
        path: '/devices',
        i18nKey: 'menu:devices',
        icon: 'MdVideocam',
        component: () => import('../views/admin/devices'),
        layout: '/admin',
      },
      {
        id: 'device-groups',
        path: '/devices/groups',
        i18nKey: 'menu:device-groups',
        icon: 'MdFolder',
        component: () => import('../views/admin/devices/DeviceGroups'),
        layout: '/admin',
      },
      {
        id: 'device-staging',
        path: '/devices/staging',
        i18nKey: 'menu:device-staging',
        icon: 'MdOutlineDeviceHub',
        component: () => import('../views/admin/devices/device-staging'),
        layout: '/admin',
      },
      {
        id: 'gb28181-devices',
        path: '/gb28181/devices',
        i18nKey: 'menu:gb28181-devices',
        icon: 'MdDeviceHub',
        component: () => import('../views/admin/gb28181/DeviceList'),
        layout: '/admin',
      },
      {
        id: 'gb28181-channels',
        path: '/gb28181/channels',
        i18nKey: 'menu:gb28181-channels',
        icon: 'MdViewList',
        component: () => import('../views/admin/gb28181/ChannelList'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'person-management',
    path: '/person-management',
    i18nKey: 'menu:person-management',
    icon: 'MdFace',
    layout: '/admin',
    children: [
      {
        id: 'persons',
        path: '/persons',
        i18nKey: 'menu:persons',
        icon: 'MdFace',
        component: () => import('../views/admin/persons'),
        layout: '/admin',
      },
      {
        id: 'person-groups',
        path: '/person-groups',
        i18nKey: 'menu:person-groups',
        icon: 'MdFolder',
        component: () => import('../views/admin/persons/groups'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'user-management',
    path: '/user-management',
    i18nKey: 'menu:user-management',
    icon: 'MdPeople',
    layout: '/admin',
    children: [
      {
        id: 'users',
        path: '/users',
        i18nKey: 'menu:users',
        icon: 'MdPerson',
        component: () => import('../views/admin/users'),
        layout: '/admin',
      },
      {
        id: 'roles',
        path: '/roles',
        i18nKey: 'menu:roles',
        icon: 'MdSecurity',
        component: () => import('../views/admin/roles'),
        layout: '/admin',
      },
      {
        id: 'permissions',
        path: '/permissions',
        i18nKey: 'menu:permissions',
        icon: 'MdVpnKey',
        component: () => import('../views/admin/permissions'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'algorithm-management',
    path: '/algorithm-management',
    i18nKey: 'menu:algorithm-management',
    icon: 'MdVpnKey',
    layout: '/admin',
    children: [
      {
        id: 'license',
        path: '/algorithm-management/license',
        i18nKey: 'menu:license',
        icon: 'MdVpnKey',
        component: () => import('../views/admin/license'),
        layout: '/admin',
      },
      {
        id: 'algorithm-packages',
        path: '/algorithm-packages',
        i18nKey: 'menu:algorithm-packages',
        icon: 'MdExtension',
        component: () => import('../views/admin/algorithmpackage'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'system-management',
    path: '/system-management',
    i18nKey: 'menu:system-management',
    icon: 'MdSettings',
    layout: '/admin',
    children: [
      {
        id: 'files',
        path: '/files',
        i18nKey: 'menu:files',
        icon: 'MdFolder',
        component: () => import('../views/admin/files'),
        layout: '/admin',
      },
      {
        id: 'audit-logs',
        path: '/audit-logs',
        i18nKey: 'menu:audit-logs',
        icon: 'MdHistory',
        component: () => import('../views/admin/audit-logs'),
        layout: '/admin',
      },
      {
        id: 'tasks',
        path: '/tasks',
        i18nKey: 'menu:tasks',
        icon: 'MdAssignment',
        component: () => import('../views/admin/tasks'),
        layout: '/admin',
      },
      {
        id: 'brand-config',
        path: '/brand-config',
        i18nKey: 'menu:brand-config',
        icon: 'MdPalette',
        component: () => import('../views/admin/brand-config'),
        layout: '/admin',
      },
      {
        id: 'mail-config',
        path: '/mail-config',
        i18nKey: 'menu:mail-config',
        icon: 'MdEmail',
        component: () => import('../views/admin/mail-config'),
        layout: '/admin',
      },
      {
        id: 'feedback',
        path: '/feedback',
        i18nKey: 'menu:feedback',
        icon: 'MdFeedback',
        component: () => import('../views/admin/feedback'),
        layout: '/admin',
      },
      {
        id: 'system-config',
        path: '/system/config',
        i18nKey: 'menu:system-config',
        icon: 'MdSettings',
        component: () => import('../views/admin/system/SystemConfig'),
        layout: '/admin',
      },
    ],
  },
];

/**
 * 认证页面路由配置
 */
export const authRoutes: RouteConfig[] = [
  {
    id: 'sign-in',
    path: '/sign-in',
    i18nKey: 'auth.login.title',
    icon: '',
    component: () => import('../views/auth/signIn'),
    layout: '/auth',
    hidden: true,
  },
];

/**
 * 所有路由配置
 */
export const allRoutes: RouteConfig[] = [...adminRoutes, ...authRoutes];

export default allRoutes;
