// Code generated by niko-admin. DO NOT EDIT.
// Route configurations
// Generate at: 2026-05-16

import { RouteConfig } from './types';

/**
 * 管理后台路由配置
 * 注意：icon 使用 react-icons 的图标名称（如 'MdHome', 'MdPerson'）
 * 在 sidebar 中会动态映射到对应的图标组件
 */
export const adminRoutes: RouteConfig[] = [
  {
    id: 'dashboard',
    path: '/default',
    i18nKey: 'menu:dashboard',
    icon: 'MdHome',
    component: () => import('../views/admin/default'),
    layout: '/admin',
  },
  {
    id: 'device-management',
    path: '/device-management',
    i18nKey: 'menu:device-management',
    icon: 'MdVideocam',
    layout: '/admin',
    children: [
      {
        id: 'devices',
        path: '/devices',
        i18nKey: 'menu:devices',
        icon: 'MdVideocam',
        component: () => import('../views/admin/devices'),
        layout: '/admin',
      },
      {
        id: 'device-groups',
        path: '/devices/groups',
        i18nKey: 'menu:device-groups',
        icon: 'MdFolder',
        component: () => import('../views/admin/devices/DeviceGroups'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'media-management',
    path: '/media-management',
    i18nKey: 'menu:media-management',
    icon: 'MdLiveTv',
    layout: '/admin',
    children: [
      {
        id: 'live-view',
        path: '/media/live',
        i18nKey: 'menu:live-view',
        icon: 'MdViewStream',
        component: () => import('../views/admin/media/MediaDashboard'),
        layout: '/admin',
      },
      {
        id: 'recordings',
        path: '/media/recordings',
        i18nKey: 'menu:recordings',
        icon: 'MdVideoLibrary',
        component: () => import('../views/admin/media/RecordingsView'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'user-management',
    path: '/user-management',
    i18nKey: 'menu:user-management',
    icon: 'MdPeople',
    layout: '/admin',
    children: [
      {
        id: 'users',
        path: '/users',
        i18nKey: 'menu:users',
        icon: 'MdPerson',
        component: () => import('../views/admin/users'),
        layout: '/admin',
      },
      {
        id: 'roles',
        path: '/roles',
        i18nKey: 'menu:roles',
        icon: 'MdSecurity',
        component: () => import('../views/admin/roles'),
        layout: '/admin',
      },
      {
        id: 'permissions',
        path: '/permissions',
        i18nKey: 'menu:permissions',
        icon: 'MdVpnKey',
        component: () => import('../views/admin/permissions'),
        layout: '/admin',
      },
    ],
  },
  {
    id: 'system-management',
    path: '/system-management',
    i18nKey: 'menu:system-management',
    icon: 'MdSettings',
    layout: '/admin',
    children: [
      {
        id: 'files',
        path: '/files',
        i18nKey: 'menu:files',
        icon: 'MdFolder',
        component: () => import('../views/admin/files'),
        layout: '/admin',
      },
      {
        id: 'audit-logs',
        path: '/audit-logs',
        i18nKey: 'menu:audit-logs',
        icon: 'MdHistory',
        component: () => import('../views/admin/audit-logs'),
        layout: '/admin',
      },
      {
        id: 'tasks',
        path: '/tasks',
        i18nKey: 'menu:tasks',
        icon: 'MdAssignment',
        component: () => import('../views/admin/tasks'),
        layout: '/admin',
      },
      {
        id: 'brand-config',
        path: '/brand-config',
        i18nKey: 'menu:brand-config',
        icon: 'MdPalette',
        component: () => import('../views/admin/brand-config'),
        layout: '/admin',
      },
      {
        id: 'mail-config',
        path: '/mail-config',
        i18nKey: 'menu:mail-config',
        icon: 'MdEmail',
        component: () => import('../views/admin/mail-config'),
        layout: '/admin',
      },
      {
        id: 'feedback',
        path: '/feedback',
        i18nKey: 'menu:feedback',
        icon: 'MdFeedback',
        component: () => import('../views/admin/feedback'),
        layout: '/admin',
      },
    ],
  },
];

/**
 * 认证页面路由配置
 */
export const authRoutes: RouteConfig[] = [
  {
    id: 'sign-in',
    path: '/sign-in',
    i18nKey: 'auth.login.title',
    icon: '',
    component: () => import('../views/auth/signIn'),
    layout: '/auth',
    hidden: true,
  },
];

/**
 * 所有路由配置
 */
export const allRoutes: RouteConfig[] = [...adminRoutes, ...authRoutes];

export default allRoutes;
