// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import "strconv"

/// 告警级别枚举
type AlarmLevel int8

const (
	AlarmLevelInfo     AlarmLevel = 0
	AlarmLevelWarning  AlarmLevel = 1
	AlarmLevelCritical AlarmLevel = 2
)

var EnumNamesAlarmLevel = map[AlarmLevel]string{
	AlarmLevelInfo:     "Info",
	AlarmLevelWarning:  "Warning",
	AlarmLevelCritical: "Critical",
}

var EnumValuesAlarmLevel = map[string]AlarmLevel{
	"Info":     AlarmLevelInfo,
	"Warning":  AlarmLevelWarning,
	"Critical": AlarmLevelCritical,
}

func (v AlarmLevel) String() string {
	if s, ok := EnumNamesAlarmLevel[v]; ok {
		return s
	}
	return "AlarmLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}
