// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 检测框
type BoundingBoxInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsBoundingBoxInfo(buf []byte, offset flatbuffers.UOffsetT) *BoundingBoxInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoundingBoxInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoundingBoxInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoundingBoxInfo(buf []byte, offset flatbuffers.UOffsetT) *BoundingBoxInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoundingBoxInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoundingBoxInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoundingBoxInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoundingBoxInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoundingBoxInfo) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *BoundingBoxInfo) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *BoundingBoxInfo) W() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateW(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *BoundingBoxInfo) H() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateH(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *BoundingBoxInfo) Confidence() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *BoundingBoxInfo) MutateConfidence(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *BoundingBoxInfo) LabelId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateLabelId(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *BoundingBoxInfo) LabelName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BoundingBoxInfo) TrackId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoundingBoxInfo) MutateTrackId(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func BoundingBoxInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func BoundingBoxInfoAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(0, x, 0)
}
func BoundingBoxInfoAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(1, y, 0)
}
func BoundingBoxInfoAddW(builder *flatbuffers.Builder, w int32) {
	builder.PrependInt32Slot(2, w, 0)
}
func BoundingBoxInfoAddH(builder *flatbuffers.Builder, h int32) {
	builder.PrependInt32Slot(3, h, 0)
}
func BoundingBoxInfoAddConfidence(builder *flatbuffers.Builder, confidence float32) {
	builder.PrependFloat32Slot(4, confidence, 0.0)
}
func BoundingBoxInfoAddLabelId(builder *flatbuffers.Builder, labelId int32) {
	builder.PrependInt32Slot(5, labelId, 0)
}
func BoundingBoxInfoAddLabelName(builder *flatbuffers.Builder, labelName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(labelName), 0)
}
func BoundingBoxInfoAddTrackId(builder *flatbuffers.Builder, trackId int32) {
	builder.PrependInt32Slot(7, trackId, 0)
}
func BoundingBoxInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
