// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import "strconv"

/// 解码硬件类型枚举
type DecodeHWType int8

const (
	DecodeHWTypeAuto         DecodeHWType = 0
	DecodeHWTypeRKMPP        DecodeHWType = 1
	DecodeHWTypeDVPP         DecodeHWType = 2
	DecodeHWTypeFFmpeg       DecodeHWType = 3
	DecodeHWTypeVideoToolbox DecodeHWType = 4
)

var EnumNamesDecodeHWType = map[DecodeHWType]string{
	DecodeHWTypeAuto:         "Auto",
	DecodeHWTypeRKMPP:        "RKMPP",
	DecodeHWTypeDVPP:         "DVPP",
	DecodeHWTypeFFmpeg:       "FFmpeg",
	DecodeHWTypeVideoToolbox: "VideoToolbox",
}

var EnumValuesDecodeHWType = map[string]DecodeHWType{
	"Auto":         DecodeHWTypeAuto,
	"RKMPP":        DecodeHWTypeRKMPP,
	"DVPP":         DecodeHWTypeDVPP,
	"FFmpeg":       DecodeHWTypeFFmpeg,
	"VideoToolbox": DecodeHWTypeVideoToolbox,
}

func (v DecodeHWType) String() string {
	if s, ok := EnumNamesDecodeHWType[v]; ok {
		return s
	}
	return "DecodeHWType(" + strconv.FormatInt(int64(v), 10) + ")"
}
