// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 推理结果 (SignalType.InferenceResult)
type InferenceResultMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsInferenceResultMsg(buf []byte, offset flatbuffers.UOffsetT) *InferenceResultMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InferenceResultMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishInferenceResultMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInferenceResultMsg(buf []byte, offset flatbuffers.UOffsetT) *InferenceResultMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InferenceResultMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInferenceResultMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InferenceResultMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InferenceResultMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InferenceResultMsg) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InferenceResultMsg) AlgoName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InferenceResultMsg) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 帧时间戳 (Unix 纳秒)
func (rcv *InferenceResultMsg) FrameTsNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 帧时间戳 (Unix 纳秒)
func (rcv *InferenceResultMsg) MutateFrameTsNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *InferenceResultMsg) FrameWidth() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InferenceResultMsg) MutateFrameWidth(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *InferenceResultMsg) FrameHeight() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InferenceResultMsg) MutateFrameHeight(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

/// 检测框列表
func (rcv *InferenceResultMsg) Detections(obj *BoundingBoxInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InferenceResultMsg) DetectionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// 检测框列表
func (rcv *InferenceResultMsg) RecordType() RecordType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return RecordType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *InferenceResultMsg) MutateRecordType(n RecordType) bool {
	return rcv._tab.MutateInt8Slot(18, int8(n))
}

func (rcv *InferenceResultMsg) AlarmType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InferenceResultMsg) AlarmLevel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 触发的绊线 ID 列表
func (rcv *InferenceResultMsg) TriggeredLineIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *InferenceResultMsg) TriggeredLineIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// 触发的绊线 ID 列表
func (rcv *InferenceResultMsg) SnapshotPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InferenceResultMsg) CropPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InferenceResultMsg) BackgroundPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 推理结果 JSON (透传)
func (rcv *InferenceResultMsg) ResultJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 推理结果 JSON (透传)
/// 推理耗时 (微秒)
func (rcv *InferenceResultMsg) InferTimeUs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// 推理耗时 (微秒)
func (rcv *InferenceResultMsg) MutateInferTimeUs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(34, n)
}

func InferenceResultMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func InferenceResultMsgAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func InferenceResultMsgAddAlgoName(builder *flatbuffers.Builder, algoName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(algoName), 0)
}
func InferenceResultMsgAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(deviceId), 0)
}
func InferenceResultMsgAddFrameTsNs(builder *flatbuffers.Builder, frameTsNs uint64) {
	builder.PrependUint64Slot(3, frameTsNs, 0)
}
func InferenceResultMsgAddFrameWidth(builder *flatbuffers.Builder, frameWidth uint32) {
	builder.PrependUint32Slot(4, frameWidth, 0)
}
func InferenceResultMsgAddFrameHeight(builder *flatbuffers.Builder, frameHeight uint32) {
	builder.PrependUint32Slot(5, frameHeight, 0)
}
func InferenceResultMsgAddDetections(builder *flatbuffers.Builder, detections flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(detections), 0)
}
func InferenceResultMsgStartDetectionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InferenceResultMsgAddRecordType(builder *flatbuffers.Builder, recordType RecordType) {
	builder.PrependInt8Slot(7, int8(recordType), 0)
}
func InferenceResultMsgAddAlarmType(builder *flatbuffers.Builder, alarmType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(alarmType), 0)
}
func InferenceResultMsgAddAlarmLevel(builder *flatbuffers.Builder, alarmLevel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(alarmLevel), 0)
}
func InferenceResultMsgAddTriggeredLineIds(builder *flatbuffers.Builder, triggeredLineIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(triggeredLineIds), 0)
}
func InferenceResultMsgStartTriggeredLineIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InferenceResultMsgAddSnapshotPath(builder *flatbuffers.Builder, snapshotPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(snapshotPath), 0)
}
func InferenceResultMsgAddCropPath(builder *flatbuffers.Builder, cropPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(cropPath), 0)
}
func InferenceResultMsgAddBackgroundPath(builder *flatbuffers.Builder, backgroundPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(backgroundPath), 0)
}
func InferenceResultMsgAddResultJson(builder *flatbuffers.Builder, resultJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(resultJson), 0)
}
func InferenceResultMsgAddInferTimeUs(builder *flatbuffers.Builder, inferTimeUs uint32) {
	builder.PrependUint32Slot(15, inferTimeUs, 0)
}
func InferenceResultMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
