// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LabelMapEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsLabelMapEntry(buf []byte, offset flatbuffers.UOffsetT) *LabelMapEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LabelMapEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishLabelMapEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLabelMapEntry(buf []byte, offset flatbuffers.UOffsetT) *LabelMapEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LabelMapEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLabelMapEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LabelMapEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LabelMapEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LabelMapEntry) LabelId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LabelMapEntry) MutateLabelId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *LabelMapEntry) CategoryCode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LabelMapEntry) MutateCategoryCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *LabelMapEntry) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LabelMapEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LabelMapEntryAddLabelId(builder *flatbuffers.Builder, labelId int32) {
	builder.PrependInt32Slot(0, labelId, 0)
}
func LabelMapEntryAddCategoryCode(builder *flatbuffers.Builder, categoryCode int32) {
	builder.PrependInt32Slot(1, categoryCode, 0)
}
func LabelMapEntryAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(displayName), 0)
}
func LabelMapEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
