// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import "strconv"

/// 信令类型枚举：区分每个消息的 payload 类型
type SignalType uint16

const (
	SignalTypeUnknown              SignalType = 0
	SignalTypeStartStream          SignalType = 256
	SignalTypeStopStream           SignalType = 257
	SignalTypeUpdateAlgoConfig     SignalType = 258
	SignalTypeUpdateStreamConfig   SignalType = 259
	SignalTypeHeartbeat            SignalType = 260
	SignalTypeStartSelfCheck       SignalType = 261
	SignalTypeFaceLibraryUpdate    SignalType = 262
	SignalTypeFaceEmbeddingExtract SignalType = 263
	SignalTypeShutdown             SignalType = 511
	SignalTypeInferenceResult      SignalType = 512
	SignalTypeStreamStatusReport   SignalType = 513
	SignalTypeAlgoLoadResult       SignalType = 514
	SignalTypeEngineMetrics        SignalType = 515
	SignalTypeHeartbeatAck         SignalType = 516
	SignalTypeError                SignalType = 768
	SignalTypeLog                  SignalType = 769
)

var EnumNamesSignalType = map[SignalType]string{
	SignalTypeUnknown:              "Unknown",
	SignalTypeStartStream:          "StartStream",
	SignalTypeStopStream:           "StopStream",
	SignalTypeUpdateAlgoConfig:     "UpdateAlgoConfig",
	SignalTypeUpdateStreamConfig:   "UpdateStreamConfig",
	SignalTypeHeartbeat:            "Heartbeat",
	SignalTypeStartSelfCheck:       "StartSelfCheck",
	SignalTypeFaceLibraryUpdate:    "FaceLibraryUpdate",
	SignalTypeFaceEmbeddingExtract: "FaceEmbeddingExtract",
	SignalTypeShutdown:             "Shutdown",
	SignalTypeInferenceResult:      "InferenceResult",
	SignalTypeStreamStatusReport:   "StreamStatusReport",
	SignalTypeAlgoLoadResult:       "AlgoLoadResult",
	SignalTypeEngineMetrics:        "EngineMetrics",
	SignalTypeHeartbeatAck:         "HeartbeatAck",
	SignalTypeError:                "Error",
	SignalTypeLog:                  "Log",
}

var EnumValuesSignalType = map[string]SignalType{
	"Unknown":              SignalTypeUnknown,
	"StartStream":          SignalTypeStartStream,
	"StopStream":           SignalTypeStopStream,
	"UpdateAlgoConfig":     SignalTypeUpdateAlgoConfig,
	"UpdateStreamConfig":   SignalTypeUpdateStreamConfig,
	"Heartbeat":            SignalTypeHeartbeat,
	"StartSelfCheck":       SignalTypeStartSelfCheck,
	"FaceLibraryUpdate":    SignalTypeFaceLibraryUpdate,
	"FaceEmbeddingExtract": SignalTypeFaceEmbeddingExtract,
	"Shutdown":             SignalTypeShutdown,
	"InferenceResult":      SignalTypeInferenceResult,
	"StreamStatusReport":   SignalTypeStreamStatusReport,
	"AlgoLoadResult":       SignalTypeAlgoLoadResult,
	"EngineMetrics":        SignalTypeEngineMetrics,
	"HeartbeatAck":         SignalTypeHeartbeatAck,
	"Error":                SignalTypeError,
	"Log":                  SignalTypeLog,
}

func (v SignalType) String() string {
	if s, ok := EnumNamesSignalType[v]; ok {
		return s
	}
	return "SignalType(" + strconv.FormatInt(int64(v), 10) + ")"
}
