// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 启动推理流指令 (SignalType.StartStream)
type StartStreamCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStartStreamCmd(buf []byte, offset flatbuffers.UOffsetT) *StartStreamCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartStreamCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStartStreamCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStartStreamCmd(buf []byte, offset flatbuffers.UOffsetT) *StartStreamCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartStreamCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStartStreamCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StartStreamCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartStreamCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartStreamCmd) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartStreamCmd) StreamUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartStreamCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartStreamCmd) DeviceName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartStreamCmd) DecodeHwType() DecodeHWType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return DecodeHWType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StartStreamCmd) MutateDecodeHwType(n DecodeHWType) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

func (rcv *StartStreamCmd) MaxReconnects() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 3
}

func (rcv *StartStreamCmd) MutateMaxReconnects(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *StartStreamCmd) ReconnectIntervalSec() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 5
}

func (rcv *StartStreamCmd) MutateReconnectIntervalSec(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

/// 绑定的算法列表 (按 sort_order 串联执行)
func (rcv *StartStreamCmd) Algorithms(obj *AlgoBinding, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StartStreamCmd) AlgorithmsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// 绑定的算法列表 (按 sort_order 串联执行)
func StartStreamCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func StartStreamCmdAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StartStreamCmdAddStreamUrl(builder *flatbuffers.Builder, streamUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(streamUrl), 0)
}
func StartStreamCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(deviceId), 0)
}
func StartStreamCmdAddDeviceName(builder *flatbuffers.Builder, deviceName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(deviceName), 0)
}
func StartStreamCmdAddDecodeHwType(builder *flatbuffers.Builder, decodeHwType DecodeHWType) {
	builder.PrependInt8Slot(4, int8(decodeHwType), 0)
}
func StartStreamCmdAddMaxReconnects(builder *flatbuffers.Builder, maxReconnects int32) {
	builder.PrependInt32Slot(5, maxReconnects, 3)
}
func StartStreamCmdAddReconnectIntervalSec(builder *flatbuffers.Builder, reconnectIntervalSec int32) {
	builder.PrependInt32Slot(6, reconnectIntervalSec, 5)
}
func StartStreamCmdAddAlgorithms(builder *flatbuffers.Builder, algorithms flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(algorithms), 0)
}
func StartStreamCmdStartAlgorithmsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StartStreamCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
