// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 启动流指令 (SignalType.StreamStart)
type StreamStartCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStartCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStartCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStartCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamStartCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamStartCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStartCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamStartCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamStartCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamStartCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStartCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStartCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStartCmd) StreamUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStartCmd) EnableInfer() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *StreamStartCmd) MutateEnableInfer(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *StreamStartCmd) EnablePlayback() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StreamStartCmd) MutateEnablePlayback(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *StreamStartCmd) PlaybackUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStartCmd) Algorithms(obj *AlgoBinding, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StreamStartCmd) AlgorithmsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StreamStartCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func StreamStartCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamStartCmdAddStreamUrl(builder *flatbuffers.Builder, streamUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(streamUrl), 0)
}
func StreamStartCmdAddEnableInfer(builder *flatbuffers.Builder, enableInfer bool) {
	builder.PrependBoolSlot(2, enableInfer, true)
}
func StreamStartCmdAddEnablePlayback(builder *flatbuffers.Builder, enablePlayback bool) {
	builder.PrependBoolSlot(3, enablePlayback, false)
}
func StreamStartCmdAddPlaybackUrl(builder *flatbuffers.Builder, playbackUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(playbackUrl), 0)
}
func StreamStartCmdAddAlgorithms(builder *flatbuffers.Builder, algorithms flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(algorithms), 0)
}
func StreamStartCmdStartAlgorithmsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StreamStartCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
