// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 停止播放指令 (SignalType.StreamPlaybackStop)
type StreamPlaybackStopCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamPlaybackStopCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamPlaybackStopCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamPlaybackStopCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamPlaybackStopCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamPlaybackStopCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamPlaybackStopCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamPlaybackStopCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamPlaybackStopCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamPlaybackStopCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamPlaybackStopCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamPlaybackStopCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamPlaybackStopCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamPlaybackStopCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamPlaybackStopCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
