// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 单流指标快照
type StreamMetrics struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamMetrics(buf []byte, offset flatbuffers.UOffsetT) *StreamMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamMetrics{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamMetrics(buf []byte, offset flatbuffers.UOffsetT) *StreamMetrics {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamMetrics{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamMetricsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamMetrics) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamMetrics) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamMetrics) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 当前队列深度 (0-5)
func (rcv *StreamMetrics) QueueDepth() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

/// 当前队列深度 (0-5)
func (rcv *StreamMetrics) MutateQueueDepth(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

/// 累计挤出帧数
func (rcv *StreamMetrics) EvictCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// 累计挤出帧数
func (rcv *StreamMetrics) MutateEvictCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

/// 最近一次推理耗时 (微秒)
func (rcv *StreamMetrics) LastInferLatencyUs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// 最近一次推理耗时 (微秒)
func (rcv *StreamMetrics) MutateLastInferLatencyUs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

/// 平均推理耗时 (微秒)
func (rcv *StreamMetrics) AvgInferLatencyUs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// 平均推理耗时 (微秒)
func (rcv *StreamMetrics) MutateAvgInferLatencyUs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

/// P95 推理耗时 (微秒)
func (rcv *StreamMetrics) P95InferLatencyUs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// P95 推理耗时 (微秒)
func (rcv *StreamMetrics) MutateP95InferLatencyUs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

/// 累计处理帧数
func (rcv *StreamMetrics) FrameCount() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 累计处理帧数
func (rcv *StreamMetrics) MutateFrameCount(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

/// 最后一帧时间戳 (Unix 纳秒)
func (rcv *StreamMetrics) LastFrameTsNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 最后一帧时间戳 (Unix 纳秒)
func (rcv *StreamMetrics) MutateLastFrameTsNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func StreamMetricsStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func StreamMetricsAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StreamMetricsAddQueueDepth(builder *flatbuffers.Builder, queueDepth byte) {
	builder.PrependByteSlot(1, queueDepth, 0)
}
func StreamMetricsAddEvictCount(builder *flatbuffers.Builder, evictCount uint32) {
	builder.PrependUint32Slot(2, evictCount, 0)
}
func StreamMetricsAddLastInferLatencyUs(builder *flatbuffers.Builder, lastInferLatencyUs uint32) {
	builder.PrependUint32Slot(3, lastInferLatencyUs, 0)
}
func StreamMetricsAddAvgInferLatencyUs(builder *flatbuffers.Builder, avgInferLatencyUs uint32) {
	builder.PrependUint32Slot(4, avgInferLatencyUs, 0)
}
func StreamMetricsAddP95InferLatencyUs(builder *flatbuffers.Builder, p95InferLatencyUs uint32) {
	builder.PrependUint32Slot(5, p95InferLatencyUs, 0)
}
func StreamMetricsAddFrameCount(builder *flatbuffers.Builder, frameCount uint64) {
	builder.PrependUint64Slot(6, frameCount, 0)
}
func StreamMetricsAddLastFrameTsNs(builder *flatbuffers.Builder, lastFrameTsNs uint64) {
	builder.PrependUint64Slot(7, lastFrameTsNs, 0)
}
func StreamMetricsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
