// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import "strconv"

/// 流状态枚举
type StreamStatus int8

const (
	StreamStatusPending      StreamStatus = 0
	StreamStatusRunning      StreamStatus = 1
	StreamStatusReconnecting StreamStatus = 2
	StreamStatusStopped      StreamStatus = 3
	StreamStatusFailed       StreamStatus = 4
)

var EnumNamesStreamStatus = map[StreamStatus]string{
	StreamStatusPending:      "Pending",
	StreamStatusRunning:      "Running",
	StreamStatusReconnecting: "Reconnecting",
	StreamStatusStopped:      "Stopped",
	StreamStatusFailed:       "Failed",
}

var EnumValuesStreamStatus = map[string]StreamStatus{
	"Pending":      StreamStatusPending,
	"Running":      StreamStatusRunning,
	"Reconnecting": StreamStatusReconnecting,
	"Stopped":      StreamStatusStopped,
	"Failed":       StreamStatusFailed,
}

func (v StreamStatus) String() string {
	if s, ok := EnumNamesStreamStatus[v]; ok {
		return s
	}
	return "StreamStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
