// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 流状态查询 (SignalType.StreamStatus)
type StreamStatusCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStatusCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStatusCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamStatusCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamStatusCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamStatusCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamStatusCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamStatusCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStatusCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStatusCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamStatusCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamStatusCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamStatusCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
