// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package controlproto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 更新算法配置指令 (SignalType.UpdateAlgoConfig)
/// 配置变更会触发热更新流程 (状态机)
type UpdateAlgoConfigCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateAlgoConfigCmd(buf []byte, offset flatbuffers.UOffsetT) *UpdateAlgoConfigCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateAlgoConfigCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishUpdateAlgoConfigCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUpdateAlgoConfigCmd(buf []byte, offset flatbuffers.UOffsetT) *UpdateAlgoConfigCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateAlgoConfigCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUpdateAlgoConfigCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UpdateAlgoConfigCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateAlgoConfigCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateAlgoConfigCmd) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateAlgoConfigCmd) AlgoName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateAlgoConfigCmd) AlgoVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateAlgoConfigCmd) PackageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateAlgoConfigCmd) SoPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 新的算法参数 (JSON 透传)
func (rcv *UpdateAlgoConfigCmd) AlgoParamsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 新的算法参数 (JSON 透传)
/// 新的 ROI/MARK/LINE 区域 (JSON 透传)
func (rcv *UpdateAlgoConfigCmd) RoiRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 新的 ROI/MARK/LINE 区域 (JSON 透传)
func (rcv *UpdateAlgoConfigCmd) MarkRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateAlgoConfigCmd) LineRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UpdateAlgoConfigCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func UpdateAlgoConfigCmdAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func UpdateAlgoConfigCmdAddAlgoName(builder *flatbuffers.Builder, algoName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(algoName), 0)
}
func UpdateAlgoConfigCmdAddAlgoVersion(builder *flatbuffers.Builder, algoVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(algoVersion), 0)
}
func UpdateAlgoConfigCmdAddPackageId(builder *flatbuffers.Builder, packageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(packageId), 0)
}
func UpdateAlgoConfigCmdAddSoPath(builder *flatbuffers.Builder, soPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(soPath), 0)
}
func UpdateAlgoConfigCmdAddAlgoParamsJson(builder *flatbuffers.Builder, algoParamsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(algoParamsJson), 0)
}
func UpdateAlgoConfigCmdAddRoiRegionsJson(builder *flatbuffers.Builder, roiRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(roiRegionsJson), 0)
}
func UpdateAlgoConfigCmdAddMarkRegionsJson(builder *flatbuffers.Builder, markRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(markRegionsJson), 0)
}
func UpdateAlgoConfigCmdAddLineRegionsJson(builder *flatbuffers.Builder, lineRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(lineRegionsJson), 0)
}
func UpdateAlgoConfigCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
