// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/ai_vision_task.go
// Generate at: 2026-06-06 16:23:33

package router

import (
	"github.com/gin-gonic/gin"

	"github.com/niko-admin/niko-admin/internal/handler"
)

// RegisterAIVisionTaskRoutes registers AIVisionTask CRUD routes.
// api 必须是已挂载 Auth + Audit 中间件的路由组。
func RegisterAIVisionTaskRoutes(api *gin.RouterGroup, h *handler.AIVisionTaskHandler, rbacMiddleware gin.HandlerFunc) {
	// 兼容历史生成路径与 OpenSpec 约定路径，避免前端动态路由/接口联调出现 404。
	registerAIVisionTaskGroup(api.Group("/aivisiontasks"), h, rbacMiddleware)
	registerAIVisionTaskGroup(api.Group("/ai-tasks"), h, rbacMiddleware)
}

func registerAIVisionTaskGroup(group *gin.RouterGroup, h *handler.AIVisionTaskHandler, rbacMiddleware gin.HandlerFunc) {
	if rbacMiddleware != nil {
		group.Use(rbacMiddleware)
	}
	group.GET("", h.List)
	group.POST("", h.Create)
	group.POST("/check-conflict", h.CheckConflict)
	group.GET("/:id", h.GetByID)
	group.PUT("/:id", h.Update)
	group.POST("/:id/restart", h.Restart)
	group.DELETE("/:id", h.Delete)
}
