// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/ai_vision_task.go
// Generate at: 2026-06-06 16:23:33

package router

import (
	"github.com/gin-gonic/gin"

	"github.com/niko-admin/niko-admin/internal/handler"
)

// RegisterAIVisionTaskRoutes registers AIVisionTask CRUD routes.
func RegisterAIVisionTaskRoutes(api *gin.RouterGroup, h *handler.AIVisionTaskHandler, authMiddleware, rbacMiddleware gin.HandlerFunc) {
	// 兼容历史生成路径与 OpenSpec 约定路径，避免前端动态路由/接口联调出现 404。
	registerAIVisionTaskGroup(api.Group("/aivisiontasks"), h, authMiddleware, rbacMiddleware)
	registerAIVisionTaskGroup(api.Group("/ai-tasks"), h, authMiddleware, rbacMiddleware)
}

func registerAIVisionTaskGroup(group *gin.RouterGroup, h *handler.AIVisionTaskHandler, authMiddleware, rbacMiddleware gin.HandlerFunc) {
	group.GET("", authMiddleware, rbacMiddleware, h.List)
	group.POST("", authMiddleware, rbacMiddleware, h.Create)
	group.POST("/check-conflict", authMiddleware, rbacMiddleware, h.CheckConflict)
	group.GET("/:id", authMiddleware, rbacMiddleware, h.GetByID)
	group.PUT("/:id", authMiddleware, rbacMiddleware, h.Update)
	group.POST("/:id/restart", authMiddleware, rbacMiddleware, h.Restart)
	group.DELETE("/:id", authMiddleware, rbacMiddleware, h.Delete)
}
