// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/ai_vision_task.go
// Generate at: 2026-06-06 16:23:33

package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// AIVisionTaskRepository handles database operations for AIVisionTask model.
type AIVisionTaskRepository struct {
	db *gorm.DB
}

// NewAIVisionTaskRepository creates a new AIVisionTaskRepository.
func NewAIVisionTaskRepository(db *gorm.DB) *AIVisionTaskRepository {
	return &AIVisionTaskRepository{db: db}
}

// WithTx returns a repository bound to the provided transaction.
func (r *AIVisionTaskRepository) WithTx(tx *gorm.DB) *AIVisionTaskRepository {
	return &AIVisionTaskRepository{db: tx}
}

// FindByID finds a aivisiontask by its ID.
func (r *AIVisionTaskRepository) FindByID(ctx context.Context, id string) (*model.AIVisionTask, error) {
	var item model.AIVisionTask
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new aivisiontask record.
func (r *AIVisionTaskRepository) Create(ctx context.Context, item *model.AIVisionTask) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves changes to a aivisiontask record.
func (r *AIVisionTaskRepository) Update(ctx context.Context, item *model.AIVisionTask) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete removes a aivisiontask by its ID.
func (r *AIVisionTaskRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.AIVisionTask{}).Error
}

// FindActiveByNode finds all ready or running tasks for a given node, excluding a specific task ID.
func (r *AIVisionTaskRepository) FindActiveByNode(ctx context.Context, nodeID, excludeTaskID string) ([]model.AIVisionTask, error) {
	query := r.db.WithContext(ctx).Where("target_node_id = ? AND status IN (?, ?)", nodeID, model.TaskStatusReady, model.TaskStatusRunning)
	if excludeTaskID != "" {
		query = query.Where("id != ?", excludeTaskID)
	}
	var items []model.AIVisionTask
	if err := query.Find(&items).Error; err != nil {
		return nil, err
	}
	return items, nil
}

// FindAllActive finds all tasks that are either ready or running.
func (r *AIVisionTaskRepository) FindAllActive(ctx context.Context, dest *[]model.AIVisionTask) error {
	return r.db.WithContext(ctx).Where("status IN (?, ?)", model.TaskStatusReady, model.TaskStatusRunning).Find(dest).Error
}

// List returns a paginated list of aivisiontasks with optional filters.
func (r *AIVisionTaskRepository) List(ctx context.Context, req dto.AIVisionTaskListRequest) ([]model.AIVisionTask, int64, error) {
	var items []model.AIVisionTask
	var total int64

	query := r.db.WithContext(ctx).Model(&model.AIVisionTask{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.AIVisionTask{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}

// FindRunningTasksByNode returns tasks that are currently running on the specified node.
func (r *AIVisionTaskRepository) FindRunningTasksByNode(ctx context.Context, nodeID string) ([]model.AIVisionTask, error) {
	var tasks []model.AIVisionTask
	err := r.db.WithContext(ctx).
		Where("target_node_id = ?", nodeID).
		Where("status = ?", model.TaskStatusRunning).
		Find(&tasks).Error
	return tasks, err
}

// SetSuspended suspends a task with a machine-determinable reason and error message.
func (r *AIVisionTaskRepository) SetSuspended(ctx context.Context, taskID string, suspendedReason string, errorMsg string) error {
	return r.db.WithContext(ctx).
		Model(&model.AIVisionTask{}).
		Where("id = ? AND status = ?", taskID, model.TaskStatusRunning).
		Updates(map[string]interface{}{
			"status":           model.TaskStatusSuspended,
			"suspended_reason": suspendedReason,
			"error_reason":     errorMsg,
		}).Error
}

// ClearSuspended restores a task from suspended to running, clearing the suspended reason and error.
func (r *AIVisionTaskRepository) ClearSuspended(ctx context.Context, taskID string) error {
	return r.db.WithContext(ctx).
		Model(&model.AIVisionTask{}).
		Where("id = ?", taskID).
		Updates(map[string]interface{}{
			"status":           model.TaskStatusRunning,
			"suspended_reason": nil,
			"error_reason":     "",
		}).Error
}

// UpdateErrorReason updates the error_reason for a suspended task without changing status or suspended_reason.
func (r *AIVisionTaskRepository) UpdateErrorReason(ctx context.Context, taskID string, errorMsg string) error {
	return r.db.WithContext(ctx).
		Model(&model.AIVisionTask{}).
		Where("id = ?", taskID).
		Update("error_reason", errorMsg).Error
}

// FindNodeOfflineSuspendedTasks returns tasks suspended due to node offline on the specified node.
func (r *AIVisionTaskRepository) FindNodeOfflineSuspendedTasks(ctx context.Context, nodeID string) ([]model.AIVisionTask, error) {
	var tasks []model.AIVisionTask
	err := r.db.WithContext(ctx).
		Where("target_node_id = ?", nodeID).
		Where("status = ?", model.TaskStatusSuspended).
		Where("suspended_reason = ?", model.SuspendedReasonNodeOffline).
		Find(&tasks).Error
	return tasks, err
}
