// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// AlgorithmPackageRepository handles database operations for AlgorithmPackage model.
type AlgorithmPackageRepository struct {
	db *gorm.DB
}

// NewAlgorithmPackageRepository creates a new AlgorithmPackageRepository.
func NewAlgorithmPackageRepository(db *gorm.DB) *AlgorithmPackageRepository {
	return &AlgorithmPackageRepository{db: db}
}

// FindByID finds a algorithmpackage by its ID.
func (r *AlgorithmPackageRepository) FindByID(ctx context.Context, id string) (*model.AlgorithmPackage, error) {
	var item model.AlgorithmPackage
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

func (r *AlgorithmPackageRepository) FindLatestPassedByAlgorithm(ctx context.Context, algoName string) (*model.AlgorithmPackage, error) {
	var item model.AlgorithmPackage
	err := r.db.WithContext(ctx).
		Where("algorithm_name = ? AND self_check_status = ?", algoName, model.SelfCheckStatusPassed).
		Order("updated_at DESC").
		First(&item).Error
	return &item, err
}

// Create inserts a new algorithmpackage record.
func (r *AlgorithmPackageRepository) Create(ctx context.Context, item *model.AlgorithmPackage) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves changes to a algorithmpackage record.
func (r *AlgorithmPackageRepository) Update(ctx context.Context, item *model.AlgorithmPackage) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete removes a algorithmpackage by its ID.
func (r *AlgorithmPackageRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.AlgorithmPackage{}).Error
}

// List returns a paginated list of algorithmpackages with optional filters.
func (r *AlgorithmPackageRepository) List(ctx context.Context, req dto.AlgorithmPackageListRequest) ([]model.AlgorithmPackage, int64, error) {
	var items []model.AlgorithmPackage
	var total int64

	query := r.db.WithContext(ctx).Model(&model.AlgorithmPackage{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.AlgorithmPackage{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}
