// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// AlgorithmLabelMapRepository handles database operations for AlgorithmLabelMap model.
type AlgorithmLabelMapRepository struct {
	db *gorm.DB
}

// NewAlgorithmLabelMapRepository creates a new AlgorithmLabelMapRepository.
func NewAlgorithmLabelMapRepository(db *gorm.DB) *AlgorithmLabelMapRepository {
	return &AlgorithmLabelMapRepository{db: db}
}

// FindByID finds a algorithmlabelmap by its ID.
func (r *AlgorithmLabelMapRepository) FindByID(ctx context.Context, id string) (*model.AlgorithmLabelMap, error) {
	var item model.AlgorithmLabelMap
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new algorithmlabelmap record.
func (r *AlgorithmLabelMapRepository) Create(ctx context.Context, item *model.AlgorithmLabelMap) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves changes to a algorithmlabelmap record.
func (r *AlgorithmLabelMapRepository) Update(ctx context.Context, item *model.AlgorithmLabelMap) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete removes a algorithmlabelmap by its ID.
func (r *AlgorithmLabelMapRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.AlgorithmLabelMap{}).Error
}

// List returns a paginated list of algorithmlabelmaps with optional filters.
func (r *AlgorithmLabelMapRepository) List(ctx context.Context, req dto.AlgorithmLabelMapListRequest) ([]model.AlgorithmLabelMap, int64, error) {
	var items []model.AlgorithmLabelMap
	var total int64

	query := r.db.WithContext(ctx).Model(&model.AlgorithmLabelMap{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.AlgorithmLabelMap{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}
