// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package repository

import (
	"context"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// CategoryCodeRepository handles database operations for CategoryCode model.
type CategoryCodeRepository struct {
	db *gorm.DB
}

// NewCategoryCodeRepository creates a new CategoryCodeRepository.
func NewCategoryCodeRepository(db *gorm.DB) *CategoryCodeRepository {
	return &CategoryCodeRepository{db: db}
}

// FindByID finds a categorycode by its ID.
func (r *CategoryCodeRepository) FindByID(ctx context.Context, id string) (*model.CategoryCode, error) {
	var item model.CategoryCode
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// Create inserts a new categorycode record.
func (r *CategoryCodeRepository) Create(ctx context.Context, item *model.CategoryCode) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update saves changes to a categorycode record.
func (r *CategoryCodeRepository) Update(ctx context.Context, item *model.CategoryCode) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// Delete removes a categorycode by its ID.
func (r *CategoryCodeRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.CategoryCode{}).Error
}

// List returns a paginated list of categorycodes with optional filters.
func (r *CategoryCodeRepository) List(ctx context.Context, req dto.CategoryCodeListRequest) ([]model.CategoryCode, int64, error) {
	var items []model.CategoryCode
	var total int64

	query := r.db.WithContext(ctx).Model(&model.CategoryCode{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.CategoryCode{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}
