// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/license.go
// Generate at: 2026-06-06 16:00:00

// Package repository 提供数据访问层实现，封装 GORM 数据库操作。
package repository

import (
	"context"
	"fmt"

	"gorm.io/gorm"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)

// LicenseRepository 处理 DeviceLicense 授权模型的数据库读写操作
type LicenseRepository struct {
	db *gorm.DB
}

// NewLicenseRepository 创建并返回一个新的 LicenseRepository 实例
func NewLicenseRepository(db *gorm.DB) *LicenseRepository {
	return &LicenseRepository{db: db}
}

// FindByID 根据主键 ID 查询单个授权记录
func (r *LicenseRepository) FindByID(ctx context.Context, id string) (*model.DeviceLicense, error) {
	var item model.DeviceLicense
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&item).Error
	return &item, err
}

// FindActive 查询当前生效的授权（状态为 active 且在有效期内）
func (r *LicenseRepository) FindActive(ctx context.Context) (*model.DeviceLicense, error) {
	var item model.DeviceLicense
	err := r.db.WithContext(ctx).
		Where("status = ?", model.LicenseStatusActive).
		Order("created_at DESC").
		First(&item).Error
	return &item, err
}

// FindByLicenseID 根据授权 ID 查询授权记录（非主键 ID）
func (r *LicenseRepository) FindByLicenseID(ctx context.Context, licenseID string) (*model.DeviceLicense, error) {
	var item model.DeviceLicense
	err := r.db.WithContext(ctx).Where("license_id = ?", licenseID).First(&item).Error
	return &item, err
}

// FindActiveByAlgorithm 查询包含指定算法的有效授权
func (r *LicenseRepository) FindActiveByAlgorithm(ctx context.Context, algoName string) (*model.DeviceLicense, error) {
	var item model.DeviceLicense
	// 使用参数化查询构建 JSON 数组匹配，避免字符串拼接
	algoJSON := fmt.Sprintf(`["%s"]`, algoName)
	err := r.db.WithContext(ctx).
		Where("status = ?", model.LicenseStatusActive).
		Where("algorithms @> ?::jsonb OR algorithms @> ?::jsonb", algoJSON, `["*"]`).
		Order("created_at DESC").
		First(&item).Error
	return &item, err
}

// Create 插入一条新的授权记录
func (r *LicenseRepository) Create(ctx context.Context, item *model.DeviceLicense) error {
	return r.db.WithContext(ctx).Create(item).Error
}

// Update 更新授权记录字段
func (r *LicenseRepository) Update(ctx context.Context, item *model.DeviceLicense) error {
	return r.db.WithContext(ctx).Save(item).Error
}

// UpdateStatus 快捷更新授权状态
func (r *LicenseRepository) UpdateStatus(ctx context.Context, id, status string) error {
	return r.db.WithContext(ctx).Model(&model.DeviceLicense{}).
		Where("id = ?", id).
		Update("status", status).Error
}

// Delete 根据 ID 删除授权记录
func (r *LicenseRepository) Delete(ctx context.Context, id string) error {
	return r.db.WithContext(ctx).Where("id = ?", id).Delete(&model.DeviceLicense{}).Error
}

// List 分页查询并返回满足筛选条件的授权列表
func (r *LicenseRepository) List(ctx context.Context, req dto.LicenseListRequest) ([]model.DeviceLicense, int64, error) {
	var items []model.DeviceLicense
	var total int64

	query := r.db.WithContext(ctx).Model(&model.DeviceLicense{}).Scopes(req.FilterScopes()...)
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}

	err := query.Scopes(
		scopes.Paginate(req.GetPage(), req.GetPageSize()),
		scopes.OrderBy(req.Sort, req.Order, model.DeviceLicense{}.SortableFields()...),
	).Find(&items).Error
	return items, total, err
}

// ListForExport 返回符合筛选条件的授权列表，用于导出。
func (r *LicenseRepository) ListForExport(ctx context.Context, req dto.LicenseListRequest, limit int) ([]model.DeviceLicense, error) {
	var items []model.DeviceLicense
	err := r.db.WithContext(ctx).
		Model(&model.DeviceLicense{}).
		Scopes(req.FilterScopes()...).
		Scopes(scopes.OrderBy(req.Sort, req.Order, model.DeviceLicense{}.SortableFields()...), scopes.OrderByDefault()).
		Limit(limit).
		Find(&items).Error
	return items, err
}
