services:
  zlmediakit:
    image: zlmediakit/zlmediakit:master
    container_name: zlmediakit
    restart: always
    network_mode: host
    volumes:
      - ./config/config.ini:/opt/media/conf/config.ini
      - ./data/www:/opt/media/www
      - ./data/record:/opt/media/record
    environment:
      - TZ=Asia/Shanghai
