// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package service

import (
	"context"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/repository"
)

// AlgorithmLabelMapService handles business logic for AlgorithmLabelMap operations.
type AlgorithmLabelMapService struct {
	algorithmlabelmapRepo *repository.AlgorithmLabelMapRepository
}

// NewAlgorithmLabelMapService creates a new AlgorithmLabelMapService.
func NewAlgorithmLabelMapService(algorithmlabelmapRepo *repository.AlgorithmLabelMapRepository) *AlgorithmLabelMapService {
	return &AlgorithmLabelMapService{ algorithmlabelmapRepo: algorithmlabelmapRepo}
}

// List returns a paginated list of algorithmlabelmaps with optional filters.
func (s *AlgorithmLabelMapService) List(ctx context.Context, req dto.AlgorithmLabelMapListRequest) ([]model.AlgorithmLabelMap, int64, error) {
	return s.algorithmlabelmapRepo.List(ctx, req)
}

// Create creates a new algorithmlabelmap.
func (s *AlgorithmLabelMapService) Create(ctx context.Context, req dto.CreateAlgorithmLabelMapRequest) (*model.AlgorithmLabelMap, error) {
	item := &model.AlgorithmLabelMap{
		PackageID: req.PackageID,
		LabelID: req.LabelID,
		CategoryCode: req.CategoryCode,
		DisplayName: req.DisplayName,
	}
	if err := s.algorithmlabelmapRepo.Create(ctx, item); err != nil {
		return nil, err
	}
	return item, nil
}

// GetByID returns a algorithmlabelmap by its ID.
func (s *AlgorithmLabelMapService) GetByID(ctx context.Context, id string) (*model.AlgorithmLabelMap, error) {
	return s.algorithmlabelmapRepo.FindByID(ctx, id)
}

// Update updates an existing algorithmlabelmap.
func (s *AlgorithmLabelMapService) Update(ctx context.Context, id string, req dto.UpdateAlgorithmLabelMapRequest) error {
	item, err := s.algorithmlabelmapRepo.FindByID(ctx, id)
	if err != nil {
		return err
	}
	if req.PackageID != "" {
		item.PackageID = req.PackageID
	}
	item.LabelID = req.LabelID
	item.CategoryCode = req.CategoryCode
	if req.DisplayName != "" {
		item.DisplayName = req.DisplayName
	}
	return s.algorithmlabelmapRepo.Update(ctx, item)
}

// Delete soft-deletes a algorithmlabelmap by its ID.
func (s *AlgorithmLabelMapService) Delete(ctx context.Context, id string) error {
	return s.algorithmlabelmapRepo.Delete(ctx, id)
}
