// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package service

import (
	"context"

	"github.com/redis/go-redis/v9"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/repository"
)

// AlgorithmPackageService handles business logic for AlgorithmPackage operations.
type AlgorithmPackageService struct {
	algorithmpackageRepo *repository.AlgorithmPackageRepository
	opts                 AlgorithmOptions
	rdb                  *redis.Client
	engine               EngineClient
}

// NewAlgorithmPackageService creates a new AlgorithmPackageService.
func NewAlgorithmPackageService(
	algorithmpackageRepo *repository.AlgorithmPackageRepository,
	opts AlgorithmOptions,
	rdb *redis.Client,
	engine EngineClient,
) *AlgorithmPackageService {
	return &AlgorithmPackageService{
		algorithmpackageRepo: algorithmpackageRepo,
		opts:                 opts,
		rdb:                  rdb,
		engine:               engine,
	}
}

// List returns a paginated list of algorithmpackages with optional filters.
func (s *AlgorithmPackageService) List(ctx context.Context, req dto.AlgorithmPackageListRequest) ([]model.AlgorithmPackage, int64, error) {
	return s.algorithmpackageRepo.List(ctx, req)
}

// Create creates a new algorithmpackage.
func (s *AlgorithmPackageService) Create(ctx context.Context, req dto.CreateAlgorithmPackageRequest) (*model.AlgorithmPackage, error) {
	item := &model.AlgorithmPackage{
		AlgorithmName: req.AlgorithmName,
		AlgorithmAlias: req.AlgorithmAlias,
		Version: req.Version,
		Domain: req.Domain,
		ResultSchema: req.ResultSchema,
		Description: req.Description,
		PackagePath: req.PackagePath,
		ExtractPath: req.ExtractPath,
		PackageSize: req.PackageSize,
		PackageMD5: req.PackageMD5,
		SoPath: req.SoPath,
		AIParamsSchema: req.AIParamsSchema,
		SelfCheckStatus: req.SelfCheckStatus,
		SelfCheckResult: req.SelfCheckResult,
		SelfCheckAt: req.SelfCheckAt,
		Status: req.Status,
		RefCount: req.RefCount,
		IsCurrent: req.IsCurrent,
		Remark: req.Remark,
	}
	if err := s.algorithmpackageRepo.Create(ctx, item); err != nil {
		return nil, err
	}
	return item, nil
}

// GetByID returns a algorithmpackage by its ID.
func (s *AlgorithmPackageService) GetByID(ctx context.Context, id string) (*model.AlgorithmPackage, error) {
	return s.algorithmpackageRepo.FindByID(ctx, id)
}

// Update updates an existing algorithmpackage.
func (s *AlgorithmPackageService) Update(ctx context.Context, id string, req dto.UpdateAlgorithmPackageRequest) error {
	item, err := s.algorithmpackageRepo.FindByID(ctx, id)
	if err != nil {
		return err
	}
	if req.AlgorithmName != "" {
		item.AlgorithmName = req.AlgorithmName
	}
	if req.AlgorithmAlias != "" {
		item.AlgorithmAlias = req.AlgorithmAlias
	}
	if req.Version != "" {
		item.Version = req.Version
	}
	if req.Domain != "" {
		item.Domain = req.Domain
	}
	if req.ResultSchema != "" {
		item.ResultSchema = req.ResultSchema
	}
	if req.Description != "" {
		item.Description = req.Description
	}
	if req.PackagePath != "" {
		item.PackagePath = req.PackagePath
	}
	if req.ExtractPath != "" {
		item.ExtractPath = req.ExtractPath
	}
	item.PackageSize = req.PackageSize
	if req.PackageMD5 != "" {
		item.PackageMD5 = req.PackageMD5
	}
	if req.SoPath != "" {
		item.SoPath = req.SoPath
	}
	item.AIParamsSchema = req.AIParamsSchema
	if req.SelfCheckStatus != "" {
		item.SelfCheckStatus = req.SelfCheckStatus
	}
	item.SelfCheckResult = req.SelfCheckResult
	if req.SelfCheckAt != nil {
		item.SelfCheckAt = req.SelfCheckAt
	}
	if req.Status != "" {
		item.Status = req.Status
	}
	item.RefCount = req.RefCount
	item.IsCurrent = req.IsCurrent
	if req.Remark != "" {
		item.Remark = req.Remark
	}
	return s.algorithmpackageRepo.Update(ctx, item)
}

// Delete soft-deletes a algorithmpackage by its ID.
func (s *AlgorithmPackageService) Delete(ctx context.Context, id string) error {
	return s.algorithmpackageRepo.Delete(ctx, id)
}
