// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package service

import (
	"context"

	"github.com/niko-admin/niko-admin/internal/dto"
	"github.com/niko-admin/niko-admin/internal/model"
	"github.com/niko-admin/niko-admin/internal/repository"
)

// CategoryCodeService handles business logic for CategoryCode operations.
type CategoryCodeService struct {
	categorycodeRepo *repository.CategoryCodeRepository
}

// NewCategoryCodeService creates a new CategoryCodeService.
func NewCategoryCodeService(categorycodeRepo *repository.CategoryCodeRepository) *CategoryCodeService {
	return &CategoryCodeService{ categorycodeRepo: categorycodeRepo}
}

// List returns a paginated list of categorycodes with optional filters.
func (s *CategoryCodeService) List(ctx context.Context, req dto.CategoryCodeListRequest) ([]model.CategoryCode, int64, error) {
	return s.categorycodeRepo.List(ctx, req)
}

// Create creates a new categorycode.
func (s *CategoryCodeService) Create(ctx context.Context, req dto.CreateCategoryCodeRequest) (*model.CategoryCode, error) {
	item := &model.CategoryCode{
		DisplayName: req.DisplayName,
		DisplayNameEN: req.DisplayNameEN,
		DisplayNameZhTW: req.DisplayNameZhTW,
		Domain: req.Domain,
		Description: req.Description,
		IsSystem: req.IsSystem,
		Enabled: req.Enabled,
	}
	if err := s.categorycodeRepo.Create(ctx, item); err != nil {
		return nil, err
	}
	return item, nil
}

// GetByID returns a categorycode by its ID.
func (s *CategoryCodeService) GetByID(ctx context.Context, id string) (*model.CategoryCode, error) {
	return s.categorycodeRepo.FindByID(ctx, id)
}

// Update updates an existing categorycode.
func (s *CategoryCodeService) Update(ctx context.Context, id string, req dto.UpdateCategoryCodeRequest) error {
	item, err := s.categorycodeRepo.FindByID(ctx, id)
	if err != nil {
		return err
	}
	if req.DisplayName != "" {
		item.DisplayName = req.DisplayName
	}
	if req.DisplayNameEN != "" {
		item.DisplayNameEN = req.DisplayNameEN
	}
	if req.DisplayNameZhTW != "" {
		item.DisplayNameZhTW = req.DisplayNameZhTW
	}
	if req.Domain != "" {
		item.Domain = req.Domain
	}
	if req.Description != "" {
		item.Description = req.Description
	}
	item.IsSystem = req.IsSystem
	item.Enabled = req.Enabled
	return s.categorycodeRepo.Update(ctx, item)
}

// Delete soft-deletes a categorycode by its ID.
func (s *CategoryCodeService) Delete(ctx context.Context, id string) error {
	return s.categorycodeRepo.Delete(ctx, id)
}
