// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 算法绑定参数
type AlgoBinding struct {
	_tab flatbuffers.Table
}

func GetRootAsAlgoBinding(buf []byte, offset flatbuffers.UOffsetT) *AlgoBinding {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AlgoBinding{}
	x.Init(buf, n+offset)
	return x
}

func FinishAlgoBindingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAlgoBinding(buf []byte, offset flatbuffers.UOffsetT) *AlgoBinding {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AlgoBinding{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAlgoBindingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AlgoBinding) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AlgoBinding) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AlgoBinding) AlgoName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoBinding) AlgoVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoBinding) PackageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoBinding) SoPath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 算法特定参数 (JSON 透传)
func (rcv *AlgoBinding) AlgoParamsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 算法特定参数 (JSON 透传)
/// ROI 多边形区域 (JSON 透传)
func (rcv *AlgoBinding) RoiRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// ROI 多边形区域 (JSON 透传)
/// MARK 屏蔽区域 (JSON 透传)
func (rcv *AlgoBinding) MarkRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// MARK 屏蔽区域 (JSON 透传)
/// LINE 绊线区域 (JSON 透传)
func (rcv *AlgoBinding) LineRegionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// LINE 绊线区域 (JSON 透传)
func (rcv *AlgoBinding) ScheduleEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AlgoBinding) MutateScheduleEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *AlgoBinding) ScheduleStart() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoBinding) ScheduleEnd() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoBinding) SortOrder() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AlgoBinding) MutateSortOrder(n int32) bool {
	return rcv._tab.MutateInt32Slot(26, n)
}

/// Label 映射表
func (rcv *AlgoBinding) LabelMaps(obj *LabelMapEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AlgoBinding) LabelMapsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Label 映射表
func AlgoBindingStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func AlgoBindingAddAlgoName(builder *flatbuffers.Builder, algoName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(algoName), 0)
}
func AlgoBindingAddAlgoVersion(builder *flatbuffers.Builder, algoVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(algoVersion), 0)
}
func AlgoBindingAddPackageId(builder *flatbuffers.Builder, packageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(packageId), 0)
}
func AlgoBindingAddSoPath(builder *flatbuffers.Builder, soPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(soPath), 0)
}
func AlgoBindingAddAlgoParamsJson(builder *flatbuffers.Builder, algoParamsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(algoParamsJson), 0)
}
func AlgoBindingAddRoiRegionsJson(builder *flatbuffers.Builder, roiRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(roiRegionsJson), 0)
}
func AlgoBindingAddMarkRegionsJson(builder *flatbuffers.Builder, markRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(markRegionsJson), 0)
}
func AlgoBindingAddLineRegionsJson(builder *flatbuffers.Builder, lineRegionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(lineRegionsJson), 0)
}
func AlgoBindingAddScheduleEnabled(builder *flatbuffers.Builder, scheduleEnabled bool) {
	builder.PrependBoolSlot(8, scheduleEnabled, false)
}
func AlgoBindingAddScheduleStart(builder *flatbuffers.Builder, scheduleStart flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(scheduleStart), 0)
}
func AlgoBindingAddScheduleEnd(builder *flatbuffers.Builder, scheduleEnd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(scheduleEnd), 0)
}
func AlgoBindingAddSortOrder(builder *flatbuffers.Builder, sortOrder int32) {
	builder.PrependInt32Slot(11, sortOrder, 0)
}
func AlgoBindingAddLabelMaps(builder *flatbuffers.Builder, labelMaps flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(labelMaps), 0)
}
func AlgoBindingStartLabelMapsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AlgoBindingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
