// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 算法加载/热更新结果 (SignalType.AlgoLoadResult)
type AlgoLoadResultMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsAlgoLoadResultMsg(buf []byte, offset flatbuffers.UOffsetT) *AlgoLoadResultMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AlgoLoadResultMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishAlgoLoadResultMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAlgoLoadResultMsg(buf []byte, offset flatbuffers.UOffsetT) *AlgoLoadResultMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AlgoLoadResultMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAlgoLoadResultMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AlgoLoadResultMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AlgoLoadResultMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AlgoLoadResultMsg) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoLoadResultMsg) AlgoName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoLoadResultMsg) AlgoVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoLoadResultMsg) PackageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 加载是否成功
func (rcv *AlgoLoadResultMsg) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

/// 加载是否成功
func (rcv *AlgoLoadResultMsg) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *AlgoLoadResultMsg) SelfCheckStatus() SelfCheckStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return SelfCheckStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AlgoLoadResultMsg) MutateSelfCheckStatus(n SelfCheckStatus) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

func (rcv *AlgoLoadResultMsg) ErrorCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AlgoLoadResultMsg) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 加载耗时 (毫秒)
func (rcv *AlgoLoadResultMsg) LoadTimeMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

/// 加载耗时 (毫秒)
func (rcv *AlgoLoadResultMsg) MutateLoadTimeMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

/// 模型占用的 NPU 内存 (字节)
func (rcv *AlgoLoadResultMsg) NpuMemoryBytes() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 模型占用的 NPU 内存 (字节)
func (rcv *AlgoLoadResultMsg) MutateNpuMemoryBytes(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func AlgoLoadResultMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func AlgoLoadResultMsgAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func AlgoLoadResultMsgAddAlgoName(builder *flatbuffers.Builder, algoName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(algoName), 0)
}
func AlgoLoadResultMsgAddAlgoVersion(builder *flatbuffers.Builder, algoVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(algoVersion), 0)
}
func AlgoLoadResultMsgAddPackageId(builder *flatbuffers.Builder, packageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(packageId), 0)
}
func AlgoLoadResultMsgAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(4, success, false)
}
func AlgoLoadResultMsgAddSelfCheckStatus(builder *flatbuffers.Builder, selfCheckStatus SelfCheckStatus) {
	builder.PrependInt8Slot(5, int8(selfCheckStatus), 0)
}
func AlgoLoadResultMsgAddErrorCode(builder *flatbuffers.Builder, errorCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(errorCode), 0)
}
func AlgoLoadResultMsgAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(errorMessage), 0)
}
func AlgoLoadResultMsgAddLoadTimeMs(builder *flatbuffers.Builder, loadTimeMs uint32) {
	builder.PrependUint32Slot(8, loadTimeMs, 0)
}
func AlgoLoadResultMsgAddNpuMemoryBytes(builder *flatbuffers.Builder, npuMemoryBytes uint64) {
	builder.PrependUint64Slot(9, npuMemoryBytes, 0)
}
func AlgoLoadResultMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
