// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 自定义固长多边形顶点数组 (最大8个顶点，不足用(0,0)填充)
type FixedPolygon struct {
	_tab flatbuffers.Struct
}

func (rcv *FixedPolygon) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FixedPolygon) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *FixedPolygon) V0(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *FixedPolygon) V1(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+8)
	return obj
}
func (rcv *FixedPolygon) V2(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+16)
	return obj
}
func (rcv *FixedPolygon) V3(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+24)
	return obj
}
func (rcv *FixedPolygon) V4(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+32)
	return obj
}
func (rcv *FixedPolygon) V5(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+40)
	return obj
}
func (rcv *FixedPolygon) V6(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+48)
	return obj
}
func (rcv *FixedPolygon) V7(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+56)
	return obj
}
func (rcv *FixedPolygon) Count() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(64))
}
func (rcv *FixedPolygon) MutateCount(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(64), n)
}

func CreateFixedPolygon(builder *flatbuffers.Builder, v0_x int32, v0_y int32, v1_x int32, v1_y int32, v2_x int32, v2_y int32, v3_x int32, v3_y int32, v4_x int32, v4_y int32, v5_x int32, v5_y int32, v6_x int32, v6_y int32, v7_x int32, v7_y int32, count uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 68)
	builder.PrependUint32(count)
	builder.Prep(4, 8)
	builder.PrependInt32(v7_y)
	builder.PrependInt32(v7_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v6_y)
	builder.PrependInt32(v6_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v5_y)
	builder.PrependInt32(v5_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v4_y)
	builder.PrependInt32(v4_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v3_y)
	builder.PrependInt32(v3_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v2_y)
	builder.PrependInt32(v2_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v1_y)
	builder.PrependInt32(v1_x)
	builder.Prep(4, 8)
	builder.PrependInt32(v0_y)
	builder.PrependInt32(v0_x)
	return builder.Offset()
}
