// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 心跳指令 (SignalType.Heartbeat)
type HeartbeatCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatCmd(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatCmd(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatCmd) Sequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeartbeatCmd) MutateSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func HeartbeatCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HeartbeatCmdAddSequence(builder *flatbuffers.Builder, sequence uint64) {
	builder.PrependUint64Slot(0, sequence, 0)
}
func HeartbeatCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
