// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 心跳回复 (SignalType.HeartbeatAck)
type HeartbeatAckMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatAckMsg(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatAckMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatAckMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatAckMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatAckMsg(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatAckMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatAckMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatAckMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatAckMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatAckMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatAckMsg) Sequence() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeartbeatAckMsg) MutateSequence(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

/// 引擎运行时长 (秒)
func (rcv *HeartbeatAckMsg) UptimeSec() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 引擎运行时长 (秒)
func (rcv *HeartbeatAckMsg) MutateUptimeSec(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func HeartbeatAckMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HeartbeatAckMsgAddSequence(builder *flatbuffers.Builder, sequence uint64) {
	builder.PrependUint64Slot(0, sequence, 0)
}
func HeartbeatAckMsgAddUptimeSec(builder *flatbuffers.Builder, uptimeSec uint64) {
	builder.PrependUint64Slot(1, uptimeSec, 0)
}
func HeartbeatAckMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
