// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// IPC 信封：所有消息的最外层包装
type IPCEnvelope struct {
	_tab flatbuffers.Table
}

func GetRootAsIPCEnvelope(buf []byte, offset flatbuffers.UOffsetT) *IPCEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IPCEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishIPCEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIPCEnvelope(buf []byte, offset flatbuffers.UOffsetT) *IPCEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IPCEnvelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIPCEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IPCEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IPCEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

/// Schema 版本号 (major*100 + minor)
func (rcv *IPCEnvelope) SchemaVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 100
}

/// Schema 版本号 (major*100 + minor)
func (rcv *IPCEnvelope) MutateSchemaVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

/// 信令类型
func (rcv *IPCEnvelope) SignalType() SignalType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return SignalType(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

/// 信令类型
func (rcv *IPCEnvelope) MutateSignalType(n SignalType) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

/// 消息序列号 (请求-响应配对)
func (rcv *IPCEnvelope) SequenceId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 消息序列号 (请求-响应配对)
func (rcv *IPCEnvelope) MutateSequenceId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

/// 发送时间戳 (Unix 纳秒)
func (rcv *IPCEnvelope) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// 发送时间戳 (Unix 纳秒)
func (rcv *IPCEnvelope) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

/// Payload 类型标识 (反射用)
func (rcv *IPCEnvelope) PayloadType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// Payload 类型标识 (反射用)
/// 实际消息体 (指向具体 table 的 root)
func (rcv *IPCEnvelope) Payload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *IPCEnvelope) PayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IPCEnvelope) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 实际消息体 (指向具体 table 的 root)
func (rcv *IPCEnvelope) MutatePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func IPCEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func IPCEnvelopeAddSchemaVersion(builder *flatbuffers.Builder, schemaVersion uint32) {
	builder.PrependUint32Slot(0, schemaVersion, 100)
}
func IPCEnvelopeAddSignalType(builder *flatbuffers.Builder, signalType SignalType) {
	builder.PrependUint16Slot(1, uint16(signalType), 0)
}
func IPCEnvelopeAddSequenceId(builder *flatbuffers.Builder, sequenceId uint64) {
	builder.PrependUint64Slot(2, sequenceId, 0)
}
func IPCEnvelopeAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(3, timestampNs, 0)
}
func IPCEnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(payloadType), 0)
}
func IPCEnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(payload), 0)
}
func IPCEnvelopeStartPayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func IPCEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
