// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import "strconv"

/// 记录类型枚举
type RecordType int8

const (
	RecordTypeCapture     RecordType = 0
	RecordTypeRecognition RecordType = 1
	RecordTypeAlarm       RecordType = 2
)

var EnumNamesRecordType = map[RecordType]string{
	RecordTypeCapture:     "Capture",
	RecordTypeRecognition: "Recognition",
	RecordTypeAlarm:       "Alarm",
}

var EnumValuesRecordType = map[string]RecordType{
	"Capture":     RecordTypeCapture,
	"Recognition": RecordTypeRecognition,
	"Alarm":       RecordTypeAlarm,
}

func (v RecordType) String() string {
	if s, ok := EnumNamesRecordType[v]; ok {
		return s
	}
	return "RecordType(" + strconv.FormatInt(int64(v), 10) + ")"
}
