// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import "strconv"

/// 自检状态枚举
type SelfCheckStatus int8

const (
	SelfCheckStatusPending SelfCheckStatus = 0
	SelfCheckStatusRunning SelfCheckStatus = 1
	SelfCheckStatusPassed  SelfCheckStatus = 2
	SelfCheckStatusFailed  SelfCheckStatus = 3
)

var EnumNamesSelfCheckStatus = map[SelfCheckStatus]string{
	SelfCheckStatusPending: "Pending",
	SelfCheckStatusRunning: "Running",
	SelfCheckStatusPassed:  "Passed",
	SelfCheckStatusFailed:  "Failed",
}

var EnumValuesSelfCheckStatus = map[string]SelfCheckStatus{
	"Pending": SelfCheckStatusPending,
	"Running": SelfCheckStatusRunning,
	"Passed":  SelfCheckStatusPassed,
	"Failed":  SelfCheckStatusFailed,
}

func (v SelfCheckStatus) String() string {
	if s, ok := EnumNamesSelfCheckStatus[v]; ok {
		return s
	}
	return "SelfCheckStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
