// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 关闭引擎指令 (SignalType.Shutdown)
type ShutdownCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsShutdownCmd(buf []byte, offset flatbuffers.UOffsetT) *ShutdownCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ShutdownCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishShutdownCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsShutdownCmd(buf []byte, offset flatbuffers.UOffsetT) *ShutdownCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ShutdownCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedShutdownCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ShutdownCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShutdownCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ShutdownCmd) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// 优雅关闭超时 (秒)
func (rcv *ShutdownCmd) GracefulTimeoutSec() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 30
}

/// 优雅关闭超时 (秒)
func (rcv *ShutdownCmd) MutateGracefulTimeoutSec(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func ShutdownCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ShutdownCmdAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(reason), 0)
}
func ShutdownCmdAddGracefulTimeoutSec(builder *flatbuffers.Builder, gracefulTimeoutSec uint32) {
	builder.PrependUint32Slot(1, gracefulTimeoutSec, 30)
}
func ShutdownCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
