// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 启动自检指令 (SignalType.StartSelfCheck)
type StartSelfCheckCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStartSelfCheckCmd(buf []byte, offset flatbuffers.UOffsetT) *StartSelfCheckCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartSelfCheckCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStartSelfCheckCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStartSelfCheckCmd(buf []byte, offset flatbuffers.UOffsetT) *StartSelfCheckCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartSelfCheckCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStartSelfCheckCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StartSelfCheckCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartSelfCheckCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartSelfCheckCmd) DownloadUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSelfCheckCmd) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSelfCheckCmd) AlgorithmName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StartSelfCheckCmd) Version() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StartSelfCheckCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StartSelfCheckCmdAddDownloadUrl(builder *flatbuffers.Builder, downloadUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(downloadUrl), 0)
}
func StartSelfCheckCmdAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(token), 0)
}
func StartSelfCheckCmdAddAlgorithmName(builder *flatbuffers.Builder, algorithmName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(algorithmName), 0)
}
func StartSelfCheckCmdAddVersion(builder *flatbuffers.Builder, version flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(version), 0)
}
func StartSelfCheckCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
