// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 停止推理流指令 (SignalType.StopStream)
type StopStreamCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStopStreamCmd(buf []byte, offset flatbuffers.UOffsetT) *StopStreamCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StopStreamCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStopStreamCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStopStreamCmd(buf []byte, offset flatbuffers.UOffsetT) *StopStreamCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StopStreamCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStopStreamCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StopStreamCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StopStreamCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StopStreamCmd) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StopStreamCmd) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StopStreamCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StopStreamCmdAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StopStreamCmdAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(reason), 0)
}
func StopStreamCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
