// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 流状态上报 (SignalType.StreamStatusReport)
type StreamStatusReportMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStatusReportMsg(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusReportMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStatusReportMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamStatusReportMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamStatusReportMsg(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusReportMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamStatusReportMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamStatusReportMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamStatusReportMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStatusReportMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStatusReportMsg) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStatusReportMsg) Status() StreamStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return StreamStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamStatusReportMsg) MutateStatus(n StreamStatus) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *StreamStatusReportMsg) ErrorCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStatusReportMsg) ErrorMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStatusReportMsg) ReconnectCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatusReportMsg) MutateReconnectCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *StreamStatusReportMsg) MaxReconnects() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatusReportMsg) MutateMaxReconnects(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func StreamStatusReportMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func StreamStatusReportMsgAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func StreamStatusReportMsgAddStatus(builder *flatbuffers.Builder, status StreamStatus) {
	builder.PrependInt8Slot(1, int8(status), 0)
}
func StreamStatusReportMsgAddErrorCode(builder *flatbuffers.Builder, errorCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(errorCode), 0)
}
func StreamStatusReportMsgAddErrorMessage(builder *flatbuffers.Builder, errorMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(errorMessage), 0)
}
func StreamStatusReportMsgAddReconnectCount(builder *flatbuffers.Builder, reconnectCount uint32) {
	builder.PrependUint32Slot(4, reconnectCount, 0)
}
func StreamStatusReportMsgAddMaxReconnects(builder *flatbuffers.Builder, maxReconnects uint32) {
	builder.PrependUint32Slot(5, maxReconnects, 0)
}
func StreamStatusReportMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
