// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 启动播放指令 (SignalType.StreamPlaybackStart)
type StreamPlaybackStartCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamPlaybackStartCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamPlaybackStartCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamPlaybackStartCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamPlaybackStartCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamPlaybackStartCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamPlaybackStartCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamPlaybackStartCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamPlaybackStartCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamPlaybackStartCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamPlaybackStartCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamPlaybackStartCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamPlaybackStartCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamPlaybackStartCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamPlaybackStartCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
