// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 停止流指令 (SignalType.StreamStop)
type StreamStopCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStopCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStopCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStopCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamStopCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamStopCmd(buf []byte, offset flatbuffers.UOffsetT) *StreamStopCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamStopCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamStopCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamStopCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStopCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStopCmd) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamStopCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamStopCmdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamStopCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
