// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 流状态响应 (SignalType.StreamStatusRsp)
type StreamStatusRspMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStatusRspMsg(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusRspMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStatusRspMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishStreamStatusRspMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStreamStatusRspMsg(buf []byte, offset flatbuffers.UOffsetT) *StreamStatusRspMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamStatusRspMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStreamStatusRspMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StreamStatusRspMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStatusRspMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStatusRspMsg) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStatusRspMsg) IsRunning() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StreamStatusRspMsg) MutateIsRunning(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *StreamStatusRspMsg) ActiveStages(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *StreamStatusRspMsg) ActiveStagesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamStatusRspMsg) QueueSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatusRspMsg) MutateQueueSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *StreamStatusRspMsg) QueueCapacity() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatusRspMsg) MutateQueueCapacity(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *StreamStatusRspMsg) PlaybackUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamStatusRspMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func StreamStatusRspMsgAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func StreamStatusRspMsgAddIsRunning(builder *flatbuffers.Builder, isRunning bool) {
	builder.PrependBoolSlot(1, isRunning, false)
}
func StreamStatusRspMsgAddActiveStages(builder *flatbuffers.Builder, activeStages flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(activeStages), 0)
}
func StreamStatusRspMsgStartActiveStagesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StreamStatusRspMsgAddQueueSize(builder *flatbuffers.Builder, queueSize uint32) {
	builder.PrependUint32Slot(3, queueSize, 0)
}
func StreamStatusRspMsgAddQueueCapacity(builder *flatbuffers.Builder, queueCapacity uint32) {
	builder.PrependUint32Slot(4, queueCapacity, 0)
}
func StreamStatusRspMsgAddPlaybackUrl(builder *flatbuffers.Builder, playbackUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(playbackUrl), 0)
}
func StreamStatusRspMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
