// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ipc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// 更新流配置指令 (SignalType.UpdateStreamConfig)
type UpdateStreamConfigCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateStreamConfigCmd(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamConfigCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateStreamConfigCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishUpdateStreamConfigCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUpdateStreamConfigCmd(buf []byte, offset flatbuffers.UOffsetT) *UpdateStreamConfigCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateStreamConfigCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUpdateStreamConfigCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UpdateStreamConfigCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateStreamConfigCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateStreamConfigCmd) TaskId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UpdateStreamConfigCmd) MaxReconnects() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamConfigCmd) MutateMaxReconnects(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *UpdateStreamConfigCmd) ReconnectIntervalSec() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UpdateStreamConfigCmd) MutateReconnectIntervalSec(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func UpdateStreamConfigCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UpdateStreamConfigCmdAddTaskId(builder *flatbuffers.Builder, taskId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(taskId), 0)
}
func UpdateStreamConfigCmdAddMaxReconnects(builder *flatbuffers.Builder, maxReconnects int32) {
	builder.PrependInt32Slot(1, maxReconnects, 0)
}
func UpdateStreamConfigCmdAddReconnectIntervalSec(builder *flatbuffers.Builder, reconnectIntervalSec int32) {
	builder.PrependInt32Slot(2, reconnectIntervalSec, 0)
}
func UpdateStreamConfigCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
