// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/ai_vision_task.go
// Generate at: 2026-06-06 16:23:33

package handler

import (
	"github.com/gin-gonic/gin"
	"gorm.io/datatypes"
	"time"

	"github.com/niko-admin/niko-admin/internal/dto"
	apperrors "github.com/niko-admin/niko-admin/internal/pkg/errors"
	"github.com/niko-admin/niko-admin/internal/pkg/response"
	"github.com/niko-admin/niko-admin/internal/service"
)

// AIVisionTaskHandler handles HTTP requests for AIVisionTask CRUD operations.
type AIVisionTaskHandler struct {
	svc *service.AIVisionTaskService
}

// NewAIVisionTaskHandler creates a new AIVisionTaskHandler with the given service.
func NewAIVisionTaskHandler(svc *service.AIVisionTaskService) *AIVisionTaskHandler {
	return &AIVisionTaskHandler{svc: svc}
}

// List returns a paginated list of aivisiontasks with optional search filters.
//
// @Summary      AIVisionTask列表
// @Description  分页查询aivisiontasks
// @Tags         aivisiontask
// @Produce      json
// @Param        page       query   int     false  "页码"      default(1)
// @Param        page_size  query   int     false  "每页数量"  default(20)
// @Param        keyword    query   string  false  "关键词搜索"
// @Success      200  {object}  dto.Response{data=dto.PageData{list=[]model.AIVisionTask}}
// @Router       /aivisiontasks [get]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) List(c *gin.Context) {
	var req dto.AIVisionTaskListRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	items, total, err := h.svc.List(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.Page(c, items, total, req.GetPage(), req.GetPageSize())
}

// Create creates a new aivisiontask.
//
// @Summary      创建aivisiontask
// @Description  创建aivisiontask
// @Tags         aivisiontask
// @Accept       json
// @Produce      json
// @Param        body  body  dto.CreateAIVisionTaskRequest  true  "信息"
// @Success      200   {object}  dto.Response{data=model.AIVisionTask}
// @Router       /aivisiontasks [post]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) Create(c *gin.Context) {
	var req dto.CreateAIVisionTaskRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	item, err := h.svc.Create(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, item)
}

// GetByID returns a aivisiontask by its ID.
//
// @Summary      获取aivisiontask详情
// @Description  根据 ID 查询aivisiontask
// @Tags         aivisiontask
// @Produce      json
// @Param        id   path   string  true  "ID"
// @Success      200  {object}  dto.Response{data=model.AIVisionTask}
// @Router       /aivisiontasks/{id} [get]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) GetByID(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	item, err := h.svc.GetByID(c.Request.Context(), id)
	if err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, item)
}

// Update updates an existing aivisiontask by its ID.
//
// @Summary      更新aivisiontask
// @Description  更新aivisiontask
// @Tags         aivisiontask
// @Accept       json
// @Produce      json
// @Param        id    path   string                    true  "ID"
// @Param        body  body  dto.UpdateAIVisionTaskRequest  true  "信息"
// @Success      200   {object}  dto.Response
// @Router       /aivisiontasks/{id} [put]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) Update(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	var req dto.UpdateAIVisionTaskRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	if err := h.svc.Update(c.Request.Context(), id, req); err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, nil)
}

// Delete soft-deletes a aivisiontask by its ID.
//
// @Summary      删除aivisiontask
// @Description  删除aivisiontask
// @Tags         aivisiontask
// @Produce      json
// @Param        id  path  string  true  "ID"
// @Success      200  {object}  dto.Response
// @Router       /aivisiontasks/{id} [delete]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	if err := h.svc.Delete(c.Request.Context(), id); err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, nil)
}

// CheckConflict 检查资源冲突
//
// @Summary      检查资源冲突
// @Description  实时检查给定的节点和时间窗是否存在重叠冲突
// @Tags         aivisiontask
// @Accept       json
// @Produce      json
// @Param        body  body  dto.CheckConflictRequest  true  "检查参数"
// @Success      200   {object}  dto.Response
// @Router       /aivisiontasks/check-conflict [post]
// @Security     BearerAuth
func (h *AIVisionTaskHandler) CheckConflict(c *gin.Context) {
	var req dto.CheckConflictRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	startDate, err := time.Parse(time.DateOnly, req.StartDate)
	if err != nil {
		response.Err(c, apperrors.New(apperrors.ErrStartTimeFormat, ""))
		return
	}
	endDate, err := time.Parse(time.DateOnly, req.EndDate)
	if err != nil {
		response.Err(c, apperrors.New(apperrors.ErrEndTimeFormat, ""))
		return
	}

	if err := h.svc.CheckResourceConflict(c.Request.Context(), req.TargetNodeID, datatypes.Date(startDate), datatypes.Date(endDate), req.TimeWindows, req.ExcludeTaskID); err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, nil)
}
