// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package handler

import (
	"github.com/gin-gonic/gin"

	"github.com/niko-admin/niko-admin/internal/dto"
	apperrors "github.com/niko-admin/niko-admin/internal/pkg/errors"
	"github.com/niko-admin/niko-admin/internal/pkg/response"
	"github.com/niko-admin/niko-admin/internal/service"
)

// AlgorithmPackageHandler handles HTTP requests for AlgorithmPackage CRUD operations.
type AlgorithmPackageHandler struct {
	svc *service.AlgorithmPackageService
}

// NewAlgorithmPackageHandler creates a new AlgorithmPackageHandler with the given service.
func NewAlgorithmPackageHandler(svc *service.AlgorithmPackageService) *AlgorithmPackageHandler {
	return &AlgorithmPackageHandler{svc: svc}
}

// List returns a paginated list of algorithmpackages with optional search filters.
//
// @Summary      AlgorithmPackage列表
// @Description  分页查询algorithmpackages
// @Tags         algorithmpackage
// @Produce      json
// @Param        page       query   int     false  "页码"      default(1)
// @Param        page_size  query   int     false  "每页数量"  default(20)
// @Param        keyword    query   string  false  "关键词搜索"
// @Success      200  {object}  dto.Response{data=dto.PageData{list=[]model.AlgorithmPackage}}
// @Router       /algorithmpackages [get]
// @Security     BearerAuth
func (h *AlgorithmPackageHandler) List(c *gin.Context) {
	var req dto.AlgorithmPackageListRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, err.Error()))
		return
	}

	items, total, err := h.svc.List(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.Page(c, items, total, req.GetPage(), req.GetPageSize())
}

// Create creates a new algorithmpackage.
//
// @Summary      创建algorithmpackage
// @Description  创建algorithmpackage
// @Tags         algorithmpackage
// @Accept       json
// @Produce      json
// @Param        body  body  dto.CreateAlgorithmPackageRequest  true  "信息"
// @Success      200   {object}  dto.Response{data=model.AlgorithmPackage}
// @Router       /algorithmpackages [post]
// @Security     BearerAuth
func (h *AlgorithmPackageHandler) Create(c *gin.Context) {
	var req dto.CreateAlgorithmPackageRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, err.Error()))
		return
	}

	item, err := h.svc.Create(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, item)
}

// GetByID returns a algorithmpackage by its ID.
//
// @Summary      获取algorithmpackage详情
// @Description  根据 ID 查询algorithmpackage
// @Tags         algorithmpackage
// @Produce      json
// @Param        id   path   string  true  "ID"
// @Success      200  {object}  dto.Response{data=model.AlgorithmPackage}
// @Router       /algorithmpackages/{id} [get]
// @Security     BearerAuth
func (h *AlgorithmPackageHandler) GetByID(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	item, err := h.svc.GetByID(c.Request.Context(), id)
	if err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, item)
}

// Update updates an existing algorithmpackage by its ID.
//
// @Summary      更新algorithmpackage
// @Description  更新algorithmpackage
// @Tags         algorithmpackage
// @Accept       json
// @Produce      json
// @Param        id    path   string                    true  "ID"
// @Param        body  body  dto.UpdateAlgorithmPackageRequest  true  "信息"
// @Success      200   {object}  dto.Response
// @Router       /algorithmpackages/{id} [put]
// @Security     BearerAuth
func (h *AlgorithmPackageHandler) Update(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	var req dto.UpdateAlgorithmPackageRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, err.Error()))
		return
	}

	if err := h.svc.Update(c.Request.Context(), id, req); err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, nil)
}

// Delete soft-deletes a algorithmpackage by its ID.
//
// @Summary      删除algorithmpackage
// @Description  删除algorithmpackage
// @Tags         algorithmpackage
// @Produce      json
// @Param        id  path  string  true  "ID"
// @Success      200  {object}  dto.Response
// @Router       /algorithmpackages/{id} [delete]
// @Security     BearerAuth
func (h *AlgorithmPackageHandler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	if err := h.svc.Delete(c.Request.Context(), id); err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, nil)
}
