// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package handler

import (
	"github.com/gin-gonic/gin"

	"github.com/niko-admin/niko-admin/internal/dto"
	apperrors "github.com/niko-admin/niko-admin/internal/pkg/errors"
	"github.com/niko-admin/niko-admin/internal/pkg/response"
	"github.com/niko-admin/niko-admin/internal/service"
)

// AlgorithmLabelMapHandler handles HTTP requests for AlgorithmLabelMap CRUD operations.
type AlgorithmLabelMapHandler struct {
	svc *service.AlgorithmLabelMapService
}

// NewAlgorithmLabelMapHandler creates a new AlgorithmLabelMapHandler with the given service.
func NewAlgorithmLabelMapHandler(svc *service.AlgorithmLabelMapService) *AlgorithmLabelMapHandler {
	return &AlgorithmLabelMapHandler{svc: svc}
}

// List returns a paginated list of algorithmlabelmaps with optional search filters.
//
// @Summary      AlgorithmLabelMap列表
// @Description  分页查询algorithmlabelmaps
// @Tags         algorithmlabelmap
// @Produce      json
// @Param        page       query   int     false  "页码"      default(1)
// @Param        page_size  query   int     false  "每页数量"  default(20)
// @Param        keyword    query   string  false  "关键词搜索"
// @Success      200  {object}  dto.Response{data=dto.PageData{list=[]model.AlgorithmLabelMap}}
// @Router       /algorithmlabelmaps [get]
// @Security     BearerAuth
func (h *AlgorithmLabelMapHandler) List(c *gin.Context) {
	var req dto.AlgorithmLabelMapListRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	items, total, err := h.svc.List(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.Page(c, items, total, req.GetPage(), req.GetPageSize())
}

// Create creates a new algorithmlabelmap.
//
// @Summary      创建algorithmlabelmap
// @Description  创建algorithmlabelmap
// @Tags         algorithmlabelmap
// @Accept       json
// @Produce      json
// @Param        body  body  dto.CreateAlgorithmLabelMapRequest  true  "信息"
// @Success      200   {object}  dto.Response{data=model.AlgorithmLabelMap}
// @Router       /algorithmlabelmaps [post]
// @Security     BearerAuth
func (h *AlgorithmLabelMapHandler) Create(c *gin.Context) {
	var req dto.CreateAlgorithmLabelMapRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	item, err := h.svc.Create(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, item)
}

// GetByID returns a algorithmlabelmap by its ID.
//
// @Summary      获取algorithmlabelmap详情
// @Description  根据 ID 查询algorithmlabelmap
// @Tags         algorithmlabelmap
// @Produce      json
// @Param        id   path   string  true  "ID"
// @Success      200  {object}  dto.Response{data=model.AlgorithmLabelMap}
// @Router       /algorithmlabelmaps/{id} [get]
// @Security     BearerAuth
func (h *AlgorithmLabelMapHandler) GetByID(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	item, err := h.svc.GetByID(c.Request.Context(), id)
	if err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, item)
}

// Update updates an existing algorithmlabelmap by its ID.
//
// @Summary      更新algorithmlabelmap
// @Description  更新algorithmlabelmap
// @Tags         algorithmlabelmap
// @Accept       json
// @Produce      json
// @Param        id    path   string                    true  "ID"
// @Param        body  body  dto.UpdateAlgorithmLabelMapRequest  true  "信息"
// @Success      200   {object}  dto.Response
// @Router       /algorithmlabelmaps/{id} [put]
// @Security     BearerAuth
func (h *AlgorithmLabelMapHandler) Update(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	var req dto.UpdateAlgorithmLabelMapRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	if err := h.svc.Update(c.Request.Context(), id, req); err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, nil)
}

// Delete soft-deletes a algorithmlabelmap by its ID.
//
// @Summary      删除algorithmlabelmap
// @Description  删除algorithmlabelmap
// @Tags         algorithmlabelmap
// @Produce      json
// @Param        id  path  string  true  "ID"
// @Success      200  {object}  dto.Response
// @Router       /algorithmlabelmaps/{id} [delete]
// @Security     BearerAuth
func (h *AlgorithmLabelMapHandler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	if err := h.svc.Delete(c.Request.Context(), id); err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, nil)
}
