// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package handler

import (
	"github.com/gin-gonic/gin"

	"github.com/niko-admin/niko-admin/internal/dto"
	apperrors "github.com/niko-admin/niko-admin/internal/pkg/errors"
	"github.com/niko-admin/niko-admin/internal/pkg/response"
	"github.com/niko-admin/niko-admin/internal/service"
)

// CategoryCodeHandler handles HTTP requests for CategoryCode CRUD operations.
type CategoryCodeHandler struct {
	svc *service.CategoryCodeService
}

// NewCategoryCodeHandler creates a new CategoryCodeHandler with the given service.
func NewCategoryCodeHandler(svc *service.CategoryCodeService) *CategoryCodeHandler {
	return &CategoryCodeHandler{svc: svc}
}

// List returns a paginated list of categorycodes with optional search filters.
//
// @Summary      CategoryCode列表
// @Description  分页查询categorycodes
// @Tags         categorycode
// @Produce      json
// @Param        page       query   int     false  "页码"      default(1)
// @Param        page_size  query   int     false  "每页数量"  default(20)
// @Param        keyword    query   string  false  "关键词搜索"
// @Success      200  {object}  dto.Response{data=dto.PageData{list=[]model.CategoryCode}}
// @Router       /categorycodes [get]
// @Security     BearerAuth
func (h *CategoryCodeHandler) List(c *gin.Context) {
	var req dto.CategoryCodeListRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	items, total, err := h.svc.List(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.Page(c, items, total, req.GetPage(), req.GetPageSize())
}

// Create creates a new categorycode.
//
// @Summary      创建categorycode
// @Description  创建categorycode
// @Tags         categorycode
// @Accept       json
// @Produce      json
// @Param        body  body  dto.CreateCategoryCodeRequest  true  "信息"
// @Success      200   {object}  dto.Response{data=model.CategoryCode}
// @Router       /categorycodes [post]
// @Security     BearerAuth
func (h *CategoryCodeHandler) Create(c *gin.Context) {
	var req dto.CreateCategoryCodeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	item, err := h.svc.Create(c.Request.Context(), req)
	if err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, item)
}

// GetByID returns a categorycode by its ID.
//
// @Summary      获取categorycode详情
// @Description  根据 ID 查询categorycode
// @Tags         categorycode
// @Produce      json
// @Param        id   path   string  true  "ID"
// @Success      200  {object}  dto.Response{data=model.CategoryCode}
// @Router       /categorycodes/{id} [get]
// @Security     BearerAuth
func (h *CategoryCodeHandler) GetByID(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	item, err := h.svc.GetByID(c.Request.Context(), id)
	if err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, item)
}

// Update updates an existing categorycode by its ID.
//
// @Summary      更新categorycode
// @Description  更新categorycode
// @Tags         categorycode
// @Accept       json
// @Produce      json
// @Param        id    path   string                    true  "ID"
// @Param        body  body  dto.UpdateCategoryCodeRequest  true  "信息"
// @Success      200   {object}  dto.Response
// @Router       /categorycodes/{id} [put]
// @Security     BearerAuth
func (h *CategoryCodeHandler) Update(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	var req dto.UpdateCategoryCodeRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		response.Err(c, badRequestError(c, err))
		return
	}

	if err := h.svc.Update(c.Request.Context(), id, req); err != nil {
		response.Err(c, err)
		return
	}

	response.OK(c, nil)
}

// Delete soft-deletes a categorycode by its ID.
//
// @Summary      删除categorycode
// @Description  删除categorycode
// @Tags         categorycode
// @Produce      json
// @Param        id  path  string  true  "ID"
// @Success      200  {object}  dto.Response
// @Router       /categorycodes/{id} [delete]
// @Security     BearerAuth
func (h *CategoryCodeHandler) Delete(c *gin.Context) {
	id := c.Param("id")
	if id == "" {
		response.Err(c, apperrors.New(apperrors.ErrBadRequest, "无效的 ID"))
		return
	}
	if err := h.svc.Delete(c.Request.Context(), id); err != nil {
		response.Err(c, err)
		return
	}
	response.OK(c, nil)
}
