// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package dto

import (
	"time"
	"gorm.io/datatypes"
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)


// CreateAlgorithmPackageRequest is the request body for creating a algorithmpackage.
type CreateAlgorithmPackageRequest struct {
	AlgorithmName string `json:"algorithm_name"`
	AlgorithmAlias string `json:"algorithm_alias,omitempty"`
	Version string `json:"version"`
	Domain string `json:"domain"`
	ResultSchema string `json:"result_schema"`
	Description string `json:"description,omitempty"`
	PackagePath string `json:"package_path"`
	ExtractPath string `json:"extract_path"`
	PackageSize int64 `json:"package_size,omitempty"`
	PackageMD5 string `json:"package_md5,omitempty"`
	SoPath string `json:"so_path"`
	AIParamsSchema datatypes.JSON `json:"ai_params_schema,omitempty"`
	SelfCheckStatus string `json:"self_check_status"`
	SelfCheckResult datatypes.JSON `json:"self_check_result,omitempty"`
	SelfCheckAt *time.Time `json:"self_check_at,omitempty"`
	Status string `json:"status"`
	RefCount int `json:"ref_count"`
	IsCurrent bool `json:"is_current"`
	Remark string `json:"remark,omitempty"`
}

// UpdateAlgorithmPackageRequest is the request body for updating a algorithmpackage.
type UpdateAlgorithmPackageRequest struct {
	AlgorithmName string `json:"algorithm_name"`
	AlgorithmAlias string `json:"algorithm_alias,omitempty"`
	Version string `json:"version"`
	Domain string `json:"domain"`
	ResultSchema string `json:"result_schema"`
	Description string `json:"description,omitempty"`
	PackagePath string `json:"package_path"`
	ExtractPath string `json:"extract_path"`
	PackageSize int64 `json:"package_size,omitempty"`
	PackageMD5 string `json:"package_md5,omitempty"`
	SoPath string `json:"so_path"`
	AIParamsSchema datatypes.JSON `json:"ai_params_schema,omitempty"`
	SelfCheckStatus string `json:"self_check_status"`
	SelfCheckResult datatypes.JSON `json:"self_check_result,omitempty"`
	SelfCheckAt *time.Time `json:"self_check_at,omitempty"`
	Status string `json:"status"`
	RefCount int `json:"ref_count"`
	IsCurrent bool `json:"is_current"`
	Remark string `json:"remark,omitempty"`
}

// AlgorithmPackageListRequest is the request for listing algorithmpackages with filters.
type AlgorithmPackageListRequest struct {
	PageRequest
	Keyword string `form:"keyword"`
}

func (r *AlgorithmPackageListRequest) FilterScopes() []scopes.Scope {
	var sc []scopes.Scope
	if r.Keyword != "" {
		sc = append(sc, scopes.MultiLike([]string{"algorithm_name", "algorithm_alias,omitempty", "version", "domain", "result_schema", "description,omitempty", "package_path", "extract_path", "package_md5,omitempty", "so_path", "self_check_status", "status", "remark,omitempty" }, r.Keyword))
	}
	return sc
}
