// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package dto

import (
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)


// CreateAlgorithmLabelMapRequest is the request body for creating a algorithmlabelmap.
type CreateAlgorithmLabelMapRequest struct {
	PackageID string `json:"package_id"`
	LabelID int `json:"label_id"`
	CategoryCode int `json:"category_code"`
	DisplayName string `json:"display_name,omitempty"`
}

// UpdateAlgorithmLabelMapRequest is the request body for updating a algorithmlabelmap.
type UpdateAlgorithmLabelMapRequest struct {
	PackageID string `json:"package_id"`
	LabelID int `json:"label_id"`
	CategoryCode int `json:"category_code"`
	DisplayName string `json:"display_name,omitempty"`
}

// AlgorithmLabelMapListRequest is the request for listing algorithmlabelmaps with filters.
type AlgorithmLabelMapListRequest struct {
	PageRequest
	Keyword string `form:"keyword"`
}

func (r *AlgorithmLabelMapListRequest) FilterScopes() []scopes.Scope {
	var sc []scopes.Scope
	if r.Keyword != "" {
		sc = append(sc, scopes.MultiLike([]string{"package_id", "display_name,omitempty" }, r.Keyword))
	}
	return sc
}
