// Code generated by niko-admin. DO NOT EDIT.
// Model: internal/model/algorithm.go
// Generate at: 2026-06-06 16:31:04

package dto

import (
	"github.com/niko-admin/niko-admin/internal/pkg/scopes"
)


// CreateCategoryCodeRequest is the request body for creating a categorycode.
type CreateCategoryCodeRequest struct {
	DisplayName string `json:"display_name"`
	DisplayNameEN string `json:"display_name_en,omitempty"`
	DisplayNameZhTW string `json:"display_name_zh_tw,omitempty"`
	Domain string `json:"domain,omitempty"`
	Description string `json:"description,omitempty"`
	IsSystem bool `json:"is_system"`
	Enabled bool `json:"enabled"`
}

// UpdateCategoryCodeRequest is the request body for updating a categorycode.
type UpdateCategoryCodeRequest struct {
	DisplayName string `json:"display_name"`
	DisplayNameEN string `json:"display_name_en,omitempty"`
	DisplayNameZhTW string `json:"display_name_zh_tw,omitempty"`
	Domain string `json:"domain,omitempty"`
	Description string `json:"description,omitempty"`
	IsSystem bool `json:"is_system"`
	Enabled bool `json:"enabled"`
}

// CategoryCodeListRequest is the request for listing categorycodes with filters.
type CategoryCodeListRequest struct {
	PageRequest
	Keyword string `form:"keyword"`
}

func (r *CategoryCodeListRequest) FilterScopes() []scopes.Scope {
	var sc []scopes.Scope
	if r.Keyword != "" {
		sc = append(sc, scopes.MultiLike([]string{"display_name", "display_name_en,omitempty", "display_name_zh_tw,omitempty", "domain,omitempty", "description,omitempty" }, r.Keyword))
	}
	return sc
}
